### ISSUE TITLE
ge6a - Draining maker through funding fee

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#125]
ge6a

high

# Draining maker through funding fee

## Summary

The funding fee is always calculated based on the direction of the basePool skew. The problem is that if another maker is used, its position change will not affect the skew of the basePool. Therefore, a user can open large positions contrary to the skew of the basePool, but in another maker, and receive funding fees for it while seriously unbalancing the second maker.

## Vulnerability Detail

Several observations:

1) The trader receives a portion of the accumulated funding fee proportionate to their notional (in the specified direction). Therefore, if a position is opened and closed in the same block, no funding fees will be accumulated. To make the attack profitable, the position can be closed as early as the next block (OP produces new blocks every 2 seconds). The longer the position is open, the more funding fees it can accumulate in case the balance of the basePool is not restored. However, the risk also increases because it is expected that the basePool balance will be restored in short periods. Also, if a position is open for a long time, a price change may occur, resulting in additional losses or gains.

2) The price pulled from the Pyth network has a maxAge = 60 seconds. Also, even with constant on-chain price updates, it will always be slightly older than the off-chain price. An attacker can use these observations to minimize their risk.

3) In low liquidity in the basePool, it can easily be skewed in a certain direction through a small position from a different address. The loss from it will be minimal compared to the funds drained from the remaining makers.

4) In the function FundingFee.getCurrentFundingRate, we have the following calculations:

    >// maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio
    // imbalanceRatio = basePool.openNotional^fundingExponentFactor / maxCapacity
    // fundingRate = fundingFactor * imbalanceRatio
    // funding = trader.openNotional * fundingRate * deltaTimeInSeconds

   From the function FundingFee._calcFundingFee(), it can be seen that the fundingFee is obtained by multiplying the trader's 
   openNotional by the change in fundingGrowthLongIndexMap[marketId]. And fundingGrowthLongIndexMap[marketId] = the sum of 
   fundingRate * time in seconds. If we can maximize the value of fundingFee, more profits can be locked in more easily during the 
   attack. This can be done by manipulating the total deposited amount by a malicious LP. If he deposits a large sum, this would 
   decrease the fundingRate and consequently the fundingFee. If he withdraws this sum, it would increase the fundingRate and 
   fundingFee. The reason is that the divisor maxCapacity changes from the calculations above.

Using the above observations, variations of the attack can be organized. I will describe one such with a Proof of Concept (POC).

Attack scenario:

1) The malicious LP deposits a large sum to keep the fundingFee low and discourage arbitrators from restoring the balance in the basePool.
2) A position is opened. The deposit is withdrawn.
3) The position is closed in the next block, locking in profits.
4) The action can be repeated as long as possible.

<details>
<summary>POC</summary>

```solidity

// drop the test into FundingFee.int.t.sol
// additional params for the setup function 
// config.setFundingConfig(marketId, 0.005e18, 1.3e18, address(maker));
// config.setMaxBorrowingFeeRate(marketId, 10000000000, 10000000000); 

function testStealFundingFee() public 
    {
        vm.prank(taker1);
        clearingHouse.openPosition(
            IClearingHouse.OpenPositionParams({
                marketId: marketId,
                maker: address(maker),
                isBaseToQuote: false,
                isExactInput: false,
                amount: 10 ether,
                oppositeAmountBound: 1000 ether,
                deadline: block.timestamp,
                makerData: ""
            })
        );

        vm.prank(taker2);
        clearingHouse.openPosition(
            IClearingHouse.OpenPositionParams({
                marketId: marketId,
                maker: address(maker2),
                isBaseToQuote: true,
                isExactInput: true,
                amount: 100 ether,
                oppositeAmountBound: 10000 ether,
                deadline: block.timestamp,
                makerData: ""
            })
        );

        vm.prank(address(maker));
        vault.transferMarginToFund(marketId, 5000e6);

        skip(2);

        vm.prank(taker2);
        clearingHouse.closePosition(
            IClearingHouse.ClosePositionParams({
                marketId: marketId,
                maker: address(maker2),
                oppositeAmountBound: 10000 ether,
                deadline: block.timestamp,
                makerData: ""
            })
        );

        console.log("Margin of taker2: %d");
        console.logInt(vault.getMargin(marketId, address(taker2)));

        console.log("Free collateral: %d", vault.getFreeCollateral(marketId, taker2, 100e18));  
    }
```
Finally, I want to note that the sponsor shared in the public Discord that whitelisted LPs are not trusted and are interested in attacks related to them.

## Impact

Loss of funds for the makers.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/fundingFee/FundingFee.sol#L104-L159

## Tool used

Manual Review

## Recommendation

Use separate funding fee instance for each maker.

Duplicate of #133

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  seem valid as the sposnor comfirm that the LPs aren't trusted; high(4)

**Comment by nirohgo** [comment]
Escalate

This should not be a dup of #133 but invalid.

Note that the scenario here involves only opening a position that benefits from an already existing funding rate set according to the Oracle Maker position skew. This by itself is not a feasible attack as gaining from it depends on many unlikely factors (a high funding rate on Oracle Maker that persists (in spite of the balancing market forces) long enough for the attacker to gain, and that the gains offset potential losses from holding the counter position long enough to gain as well as the borrowing fees the attacker pays.

#133 describes a specific attack involving actively enhancing the funding rate while holding a benefiting position on the other maker in a way that generates large gains within one block with minimal risk  (demonstrated with specific numbers through a POC.)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should not be a dup of #133 but invalid.
> 
> Note that the scenario here involves only opening a position that benefits from an already existing funding rate set according to the Oracle Maker position skew. This by itself is not a feasible attack as gaining from it depends on many unlikely factors (a high funding rate on Oracle Maker that persists (in spite of the balancing market forces) long enough for the attacker to gain, and that the gains offset potential losses from holding the counter position long enough to gain as well as the borrowing fees the attacker pays.
> 
> #133 describes a specific attack involving actively enhancing the funding rate while holding a benefiting position on the other maker in a way that generates large gains within one block with minimal risk  (demonstrated with specific numbers through a POC.)
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@paco0x @CheshireCatNick Could you take a look at this issue just in case it is not a duplicate of #133? Imo it seems very similar.

**Comment by paco0x** [comment]
I agree with @nirohgo that there're some nuances between this one and #133, this attack requires stricter conditions:

- liquidity in Oracle Maker is relatively low and attacker can deposit large amount of collaterals in to Oracle Maker
- the positions already existed in the Oracle Maker can result in a high funding rate after attacker remove liquidity

I think this is still valid but with a medium severity.

**Comment by gstoyanovbg** [comment]
I disagree with the escalation.

I really hope you don't think it's possible for me to write this report without knowing about the most obvious attack path following directly from the terminology used :)

Joking aside, I deliberately chose to present another attack path because I believe that the risks are lower. Let's take a look at what the risks are for the obvious attack path by opening a large position in the oracle maker:

1. Opening a large position can lead to serious losses due to an unfavorable change in price. Only weird tokens are excluded from this contest, so tokens with high volatility are in scope. Even for a single block, there can be a change of several percent or even more. It is true that two opposite positions are opened, but there is no guarantee that they will always be of equal value to offset the profits and losses. I believe that in most cases they will not be.

2. It is characteristic of trading that a large number of operations are performed in a short period of time (for example, opening/closing positions). The attacker has no way of knowing what operations will be performed in the corresponding block and therefore cannot be sure that the attack will be profitable, because the remaining operations of other traders may unintentionally restore the balance between long/short positions. Even if it is not fully restored, the attack may simply become unprofitable.

3. Gas fees on Optimism are low (0.1 gwei), but those on Blast are even lower (0.001 gwei). An MEV bot can constantly execute transactions that are included in every or almost every block. These transactions will monitor for the possibility of extracting funding fees by balancing the oracle maker. This way, the probability of such a transaction being executed in the same block in which the exploiter opens a position, but after it, is very high. If the MEV bot succeeds, it means that the attack will not be successful and the exploiter will only have losses from the operation.

The purpose of the example attack from my original report is to reduce these risks by depositing large liquidity from LP instead of opening a large position. This significantly reduces the risk of losses caused by big price changes and in case the attack is not profitable, it will not be a big loss either, which means that the described scenario can be executed an unlimited number of times and it is certain that some of the iterations will be successful and profits will be realized.

I believe that have the arguments to dispute the validity of report #133 following the logic from the escalation of my report.

**Comment by nevillehuang** [comment]
I believe based on sponsor comment this should remain duplicate of #133, despite it nuances. @gstoyanovbg I don't see any arguments that indicates that #133 should be invalid.

**Comment by nirohgo** [comment]
@nevillehuang @paco0x  if the attacker deposits a large amount of liquidity - the funding rate drops. Then if they remove it shortly after the rate just goes back to what it was so that's not really an attack. Alternatively they need to maintain a large enough share of total liquidity long term in hope that an opportunity comes where removing the liquidity bumps the rate such that enough profit can be made in a few blocks to justify such a costly/risky attack. Doesn't seem like a feasible attack to me, and no POC/specific numbers were provided to show that it is.

**Comment by paco0x** [comment]
> @nevillehuang @paco0x if the attacker deposits a large amount of liquidity - the funding rate drops. Then if they remove it shortly after the rate just goes back to what it was so that's not really an attack. Alternatively they need to maintain a large enough share of total liquidity long term in hope that an opportunity comes where removing the liquidity bumps the rate such that enough profit can be made in a few blocks to justify such a costly/risky attack. Doesn't seem like a feasible attack to me, and no POC/specific numbers were provided to show that it is.

I agree with your point that the liquidity requirement makes it harder to assume an attack. I'll leave it to the judge to determine the final result.

**Comment by WangSecurity** [comment]
I believe this issue identifies the core issue and provides an attack path. According to duplication rules, Scenario A, C -> medium severity attack path/just identifying the vulnerability.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #133

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nirohgo](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/125/#issuecomment-2041425606): rejected
