### ISSUE TITLE
IllIllI - Whale LPs can make the admin's risk control parameters ineffective

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#127]
IllIllI

high

# Whale LPs can make the admin's risk control parameters ineffective

## Summary

Unlike other exchanges where the funding fee is used to incentivize the perpetual price to match the spot price, the Perpetual exchange always offers the spot price, and uses the funding fee to balance the much smaller OracleMaker's position exposure. Because the OracleMaker's position is much smaller than the exchange as a whole's position balance, it's much easier to manipulate than a normal exchange, and therefore will require more frequent changes to funding-related parameters controlled by the admin. The funding fee rate depends not only on admin-controlled parameters, but with the amount of LP funds available, which is under the control of the LPs.

## Vulnerability Detail

As the setup for the attack, a well-funded attacker (e.g. a competing exchange) can use sock puppets to add LP liquidity to the OracleMaker. When the funding rate needs to be modified (e.g. because the attacker decides to spend funds to drastically skew the OracleMaker's position balance), after the admin makes the change, the attacker can magnify the effect of the parameter by withdrawing the LP liquidity, or they can mute it by adding a lot of liquidity. Because the circuitbreaker nets in-flows against out-flows, the attacker can prevent hitting the limit by depositing margin to an arbitrary position, prior to calling `withdraw()` on the OracleMaker.

## Impact

Traders expecting to be paid a funding fee for taking their positions, can suddenly find themselves having to _pay_, at the maximum rate. Customers will not use an exchange where the funding fee suddenly flips, and can't be reliably hedged/arbitraged against another exchange's funding fee.

## Code Snippet

The factor and exponent set by the admin are modulated by the capacity, which is based on the maximum leverage available, given the total amount deposited by the LPs:
```solidity
// File: src/fundingFee/FundingFee.sol : FundingFee.getCurrentFundingRate()   #1

123            uint256 totalDepositedAmount = uint256(_getVault().getSettledMargin(marketId, fundingConfig.basePool));
124            uint256 maxCapacity = FixedPointMathLib.divWad(
125 @>             totalDepositedAmount,
126                uint256(OracleMaker(fundingConfig.basePool).minMarginRatio())
127            );
128    
129            // maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio
130            // imbalanceRatio = basePool.openNotional^fundingExponentFactor / maxCapacity
131            // fundingRate = fundingFactor * imbalanceRatio
132            // funding = trader.openNotional * fundingRate * deltaTimeInSeconds
133            uint256 fundingRateAbs = FixedPointMathLib.fullMulDiv(
134 @>             fundingConfig.fundingFactor,
135                FixedPointMathLib
136 @>                 .powWad(openNotionalAbs.toInt256(), fundingConfig.fundingExponentFactor.toInt256())
137                    .toUint256(),
138 @>             maxCapacity
139:           );
```
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/fundingFee/FundingFee.sol#L123-L139

## Tool used

Manual Review

## Recommendation

Rate-limit or time-lock changes to the OracleMaker's LP levels

**Comment by sherlock-admin3** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  this seem valid medium to me due the likelihood and the admin intervention part which will definetly raise am alarm; medium(1)

**Comment by 42bchen** [comment]
Update: The funding fee can't be reversed in this assumption because the sign of the funding is based on the position direction that OracleMaker holds. It can only change the fundingRateAbs. Also, I think the severity of this problem is at most medium.

**Comment by nirohgo** [comment]
Escalate
Shoud be Invalid:
1. When admins change the funding rate configs, if a re-adjustment in needed afterwards (this is expected since liquidity shifts can happen weather or not it's done as an attack) the admin can adjust the rate again (admins are trusted - among other things to adjust configurations as needed).
2. The cost of this attack: maintaining an army of "sock-puppets" to make significant LP changes without being black listed, deploying large amounts of capital to push in/out of the Oracle Maker etc.
3. Given the ineffectiveness of the attack compared to its cost this is a non-issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> Shoud be Invalid:
> 1. When admins change the funding rate configs, if a re-adjustment in needed afterwards (this is expected since liquidity shifts can happen weather or not it's done as an attack) the admin can adjust the rate again (admins are trusted - among other things to adjust configurations as needed).
> 2. The cost of this attack: maintaining an army of "sock-puppets" to make significant LP changes without being black listed, deploying large amounts of capital to push in/out of the Oracle Maker etc.
> 3. Given the ineffectiveness of the attack compared to its cost this is a non-issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by IllIllI000** [comment]
An admin can't realistically be expected to sit there, continuously fiddling with parameters to counteract one specific user. A single user should not be able to cause problems for all other users. The escalating watson themselves in their own submission points out that one block of misaligned parameters is enough time for bad effects to occur ([scenarios B and C](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/133)). There is no blacklist, so the only option is to disable LPs, which will block users from withdrawing, as well as depositing unless they're explicitly added to a whitelist. As is mentioned in the submission, an attacker could be another exchange trying to scare away customers. All it takes is one big incident in the beginning of an exchange's life to, to cause a snowball effect of users not trusting it, and the exchange never gaining back market share.

**Comment by nirohgo** [comment]
> An admin can't realistically be expected to sit there, continuously fiddling with parameters to counteract one specific user. 

You're assuming that the funding rate configs need to be adjusted with every liquidity change, which is not the case (otherwise admins would really need to sit there all day and adjust because liquidity changes all the time). The funding rate is meant to change with liquidity: more liquidity - less risk per skew, less liquidity - more risk per skew. The parameters only affect how steep the curve is. So adding/removing liquidity does not mute/magnify the configs. It only affects the rate as expected and therefore not really an attack.

**Comment by IllIllI000** [comment]
how steep the curve is, is under the control of the attacker, and the steepness is _multiplied_ by the skew, so it's a distinction without a difference when it comes to magnifying scenarios B and C, which you point out only need one/two blocks in order to perform an attack

**Comment by nevillehuang** [comment]
@nirohgo @IllIllI000 What is the impact of loss relative to cost of attack? Maybe a scenario/PoC would help in clarifying things

**Comment by nirohgo** [comment]
> @nirohgo @IllIllI000 What is the impact of loss relative to cost of attack? Maybe a scenario/PoC would help in clarifying things

@nevillehuang  my argument is that there is no loss because the is no attack. Funding fee configs affect the shape of the fee curve, while liquidity (together with the skew size) determine where on the curve the fee should be at a given moment (as in, the ratio of skew size to max capacity represents the current risk). So basically the 'attacker' adding/removing liquidity just causes the funding fee ratio to act as intended based on the set configs and the current risk level. (also, there is no real way to know when the configs will change ahead of time, so removing liquidity means you need to hold liquidity long term, so the "attack" is basically holding or removing liquidity just like any other liquidity provider).

**Comment by IllIllI000** [comment]
@nevillehuang there is zero cost to the attacker (other than having the capital not being productive elsewhere), because there are no fees for deposit/withdraw. If you take the poc nirohgo provided in https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/133 , and change the `// initial oracle maker deposit: $2M (1000 base tokens)` from `2000000*1e6` to `2 * 2000000*1e6` in both locations, the output changes to `Exploiter Quote balance at End: 5452082158160`, which shows that adding liquidity mutes the attack, and withdrawing liquidity enhances it.

**Comment by nirohgo** [comment]
> @nevillehuang there is zero cost to the attacker (other than having the capital not being productive elsewhere), because there are no fees for deposit/withdraw. If you take the poc nirohgo provided in #133 , and change the `// initial oracle maker deposit: $2M (1000 base tokens)` from `2000000*1e6` to `2 * 2000000*1e6` in both locations, the output changes to `Exploiter Quote balance at End: 5452082158160`, which shows that adding liquidity mutes the attack, and withdrawing liquidity enhances it.

This finding has nothing to do with #133. It claims that adding/removing liquidity mutes the effects of admin parameter settings (which I've shown it doesn't), not an attack in another finding.

**Comment by IllIllI000** [comment]
And further, if you modify the config parameters to be `config.setFundingConfig(marketId, 0.005e18, 1.0e18, address(oracle_maker));` i.e. `1.2e18` -> `1.0e18`, the POC for #133 shows that there's no longer a profit

**Comment by WangSecurity** [comment]
Need additional clarification, the config defines the curve, correct? Can you briefly explain how it's intended to work with a small numeric example? @IllIllI000 @nirohgo

**Comment by IllIllI000** [comment]
@WangSecurity This [desmos](https://www.desmos.com/calculator/n4ilkhsbn1) calculator (from the [docs](https://perp.notion.site/Long-Short-Skew-Funding-Fee-fd7af74f74644209baf0ffb562dc4271)) shows the effect the OM LP can have on the funding rate per second. It starts at x(`b`)=100, y(`f`)=0.15 per dollar per second. If the admin changes the exponent from 1.74 to 1.64 in order to reduce the funding per dollar per second to 0.1, the attacker can change to b=190 in order to get it back to the original 0.15. As I point out above, it can either inflate or mute the attacker's profit shown in #133 . The vulnerability that I point out in the submission is that it's easy to manipulate it since it's not a market-wide measure, and can be done by a single malicious user, for that same user's benefit. Please let me know if you're asking for something else

**Comment by nirohgo** [comment]
> @WangSecurity This [desmos](https://www.desmos.com/calculator/n4ilkhsbn1) calculator (from the [docs](https://perp.notion.site/Long-Short-Skew-Funding-Fee-fd7af74f74644209baf0ffb562dc4271)) shows the effect the OM LP can have on the funding rate per second. It starts at x(`b`)=100, y(`f`)=0.15 per dollar per second. If the admin changes the exponent from 1.74 to 1.64 in order to reduce the funding per dollar per second to 0.1, the attacker can change to b=190 in order to get it back to the original 0.15. As I point out above, it can either inflate or mute the attacker's profit shown in #133 . The vulnerability that I point out in the submission is that it's easy to manipulate it since it's not a market-wide measure, and can be done by a single malicious user, for that same user's benefit. Please let me know if you're asking for something else

This analysis is inaccurate because it assumes that the intention of the exponent was to be set differently with every liquidity change (which I believe does not makes sense as it would require the team to constantly change this config, since liquidity keeps changing). Be that as it may , this finding is invalid because of the other point in my escalation which is that there's no real way for the exploiter to know when the config in going to change, which means in order to remove liquidity in a way that has a significant enough effect they need to hold large amounts of liquidity (the majority of total liquidity) long term hoping the config changes at some point is away that can generate profit within a block or two. The Watson hasn't shown any concrete example/POC/numbers proving this is a feasible attack.

**Comment by IllIllI000** [comment]
@WangSecurity please let me know if you have any further questions for me on this - I believe the calculator output in my example speaks for itself in spite of what nirohgo is saying

**Comment by WangSecurity** [comment]
I think now I need a bit of clarification on your attack @IllIllI000 

Basically, the LP can manipulate the funding rate. For example, if there's a big LP in the pool, and funding rate is X, the funding configs are changed to Y. When the big LP withdraws their funds, the funding rate is changed back to X, correct?

If that's correct, then as I understand the funding rate should be calculated on the amount and the size of trades, not liquidity in the pool, correct?

**Comment by IllIllI000** [comment]
Yes to both. Generally funding fees are based on the open interest, not LP liquidity, since open interest is exposed to price movement and therefore is harder to manipulate, whereas LP liquidity is not.

**Comment by WangSecurity** [comment]
As I see from the docs and the code comments in your code snippet in this report, it's intended design to account for the LP in funding tate (i.e. maxCapacity). Moreover, in comment by the sponsor [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/127#issuecomment-2019335928) we can see that it's impossible to change the sign of the funding fee.

If my second assumption reharding the sign is correct, then I believe there is no attack and this issue is a design improvement to make funding fee independent from the LP balance. Planning to accept the escalation and invalidate the issue.

**Comment by IllIllI000** [comment]
Fair enough

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nirohgo](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/127/#issuecomment-2041327361): accepted

**Comment by WangSecurity** [comment]
After additional revision of the report, the decision is that in facts identifies the same core issue as #133. In both reports, the users are able to intentionally increase funding to extreme rates. #133 describes other impacts that arise from extreme funding rate as well, but this report qualifies for being a valid duplicate under Sherlock's Duplication rules, Scenario A, Report C:

> C -> medium severity attack path/just identifying the vulnerability.

Hence, this report is duplicated with #133
