### ISSUE TITLE
IllIllI - Oracle updates can be front-run in order to bypass price band caps

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#128]
IllIllI

high

# Oracle updates can be front-run in order to bypass price band caps

## Summary

Price band caps rely on the currently-reported oracle price, which can be front-run

## Vulnerability Detail

One of the [links](https://web.archive.org/web/20230930164653/https://sips.synthetix.io/sips/sip-285/#rationale) referenced in the [code comments](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/OracleMaker.sol#L24-L30) calculates that on average, the price reported by the Pyth oracle is delayed by three seconds - one second of Binance time, and two seconds of wormhole/Pyth time. The code comments go on to say that this is the reason why `any trade on OracleMaker must be 2-step, aka "delayed"`. The contest readme emphasizes this by saying that issues where the OracleMaker's relayers don't delay for long enough, are [out of scope](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/README.md?plain=1#L62). This indicates that the belief is that there is no oracle front-run risk with the SpotHedgeBaseMaker, which is not the case.

An attacker can:
1. Watch the Binance price and wait for the price to gap from price `X` to price `Y`, keeping track of the Pyth signatures for each price
2. Update the Pyth price with the stalest still-valid signed price (price `X`)
3. Attack the SpotHedgeBaseMaker as is outlined in my other submission, such that the exchange rate is skewed to the level it would have been, had the price still been `X`, when in reality it will be closer to `Y`
4. Update the Pyth price with the freshest still-valid signed price (price `Y`)
5. Close the trade against the SpotHedgeBaseMaker at the prevailing market rate (price `Y`)

## Impact

As long as the price difference between prices `X` and `Y` is enough to cover the UniswapV3 swap fees, the attacker can make a risk-free profit at the expense of the SpotHedgeBaseMaker's LPs. Note that unlike is the case for my other submission, this attack cannot be prevented by having the price band that exactly match the UniswapV3 swap fee, so I've marked this one as High, and the other as a Medium.

## Code Snippet

The SpotHedgeBaseMaker doesn't require that the [sender](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L281) be the [Gateway/GatewayV2](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L231-L232), so anyone can execute it directly from the ClearingHouse:
```solidity
// File: src/maker/SpotHedgeBaseMaker.sol : SpotHedgeBaseMaker.isValidSender()   #1

514        function isValidSender(address) external pure override returns (bool) {
515            return true;
516:       }
```
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L504-L526

## Tool used

Manual Review

## Recommendation

Require that SpotHedgeBaseMaker be executed by a relayer

Duplicate of #119

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  the stalest dtill-valid should not count as the pyth is expected to provide an accurate data according to the readMe.

**Comment by paco0x** [comment]
This report is similar with #119, but #119 will be restricted by the price band since the trade price through AMM deviates too much from the oracle price.

This report can be utilized to intentionally cause bad debt and bypass the price band restriction.

Prerequisite:
- There's a significant price fluctuations in the short term (60s)
- No one else trade in the market during last 60s

Steps:
- Assuming price band is configured to 10%, TokenA price increases from 100 to 115 (> 10%) in 60s and no one else trades in this market 
- Attacker update the price to 100 
- Attacker manipulate the the TokenA price in AMM to ~100
- Attacker uses 2 accounts, accountA opens a 10x long, and accountB opens a 10x short, with SHBM
- Attacker make sure the avg trade price is around 100, so the price band is bypassed
- Attacker manipulate the AMM back to sync with external price
- Attacker update the price to 115
- accountB is now in bad debt and accountA profits more than accountB's collateral, close accountA's position with Oracle Maker and take profit
- The costs is the fess to manipulate AMM (2 swaps) and fees in Perp V3 (2 swaps, we'll have fees in later version)
- The spot hedge maker is always hedged and no loss happen

I agree this is a valid issue, although the part about bad debt was not mentioned. cc @IllIllI000

**Comment by IllIllI000** [comment]
@paco0x #119 mentions `abandon the perp account worth -$4k` where the negative 4k is meant to indicate bad debt, and this submission mentions `Attack the SpotHedgeBaseMaker as is outlined in my other submission`. Do you agree that this is _not_ a duplicate of #136, and that #128 should be split from 136, and that 136 should remain invalid?

**Comment by paco0x** [comment]
> @paco0x #119 mentions `abandon the perp account worth -$4k` where the negative 4k is meant to indicate bad debt, and this submission mentions `Attack the SpotHedgeBaseMaker as is outlined in my other submission`. Do you agree that this is _not_ a duplicate of #136, and that #128 should be split from 136, and that 136 should remain invalid?

yes I agree

**Comment by nevillehuang** [comment]
@paco0x What is the difference between this and #123 and/or #119. Both seems to be pointing to attacker abusing pyth oracle updates to gain a favorable price.

**Comment by paco0x** [comment]
> @paco0x What is the difference between this and #123 and/or #119. Both seems to be pointing to attacker abusing pyth oracle updates to gain a favorable price.


I think this issue is similar to #119 but different from #123.

#128/#119 both use stale price and price fluctuation to intentionally cause a bad debt in the trader's account and profit from it. And if the price fluctuations are not significant enough to cause bad debts, attackers cannot profit.

While #123 doesn't need to create a bad debt to profit, the requirements for price volatility are not that high. And the profit comes from harming the income of other LPs.

So the common point: 
- Taking advantage of the stale prices, there must be no trading activity for a while.

Difference: 
- The source of income
- The strictness of the preconditions (I think the prerequisites for #128 & #119 are more stringent. However, the risks may be even greater.)

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/perpetual-protocol/perp-contract-v3/pull/19

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
