### ISSUE TITLE
Kose - Unfair LP Fund Losses in SpotHedgeBaseMaker Due to CircuitBreaker Rate-Limiting

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#130]
Kose

medium

# Unfair LP Fund Losses in SpotHedgeBaseMaker Due to CircuitBreaker Rate-Limiting

## Summary
SpotHedgeBaseMaker LPs Face Unfair Fund Losses Due to CircuitBreaker Rate-Limiting and Vault.withdraw() Usage in Long Positions that opened using HedgeMaker as a maker.
## Vulnerability Detail
CircuitBreaker can prevent from withdrawing for some amount of time if there has been massive withdraws from protocol in the last withdrawalPeriod. To make it easier to understand let's use perpetual documentation regarding CircuitBreaker:
>  1. For instance, assume:
    a. we have total 1m deposited usdc
    b. we set `constructor(3 days, 4 hours, 1 hour)` 
    c. we set `registerAsset(usdc, 5000, 0e6)`
 > 2. If within 4 hours, total withdrawal amount ≥ 50% of 1m, it triggers rate limit
  >3. In 3 days, no one can withdraw. this is the period we can investigate. After 3 days, anyone can call `overrideExpiredRateLimit()` to override/reset the rate limit, so users can claim their funds by calling `claimLockedFunds()`
 >   4. If we found it’s an expliot during `_rateLimitCooldownPeriod`, admin can call `markAsNotOperational()` to prevent any future deposit / withdraw / claimLockedFund

The problem is during this period, SpotHedgeBaseMaker became vulnerable because it tries to use withdraw() functionality from vault if position opened against HedgeMaker is long. Hence HedgeMaker can only be used against short positions in this period where it is not possible to withdraw from vault. Malicious traders can open large amounts of short positions against HedgeMaker in this period. Also it is not a necessity for traders to act maliciously, it might not be a malicious action, just a profitable action as I will explain in the next scenario:

In the case of market crash, both will be more likely since base token's value will be decreasing massively hence it will be profitable to open short positions against HedgeMaker, and also during market crashes it is more likely for CircuitBreaker to rateLimit the system because users will try to leave the market more than likely. 

In the end of this period, HedgeMaker's position in vault will be in lost and even can be below liquidation threshold. Since it is not possible to liquidate HedgeMaker currently, it will continue to lose value.

It is also important to mention that in order for a liquidity provider to withdraw from HedgeMaker, they should first open a position that withdraws funds from vault (hence decrease it's short exposure), hence this also won't be possible in this period.

In extreme cases it is even possible that HedgeMaker accountValue in vault can end up with nearly 0 hence all LP's can lose all funds they have deposited.

## Impact
Fund loss for liquidity providers in SpotHedgeBaseMaker with amount of loss increasing as we go from normal to edge cases.
## Code Snippet
[SpotHedgeBaseMaker.sol/withdraw()](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol/#L303)
[SpotHedgeBaseMaker.sol/fillOrder()](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol/#L365)
[SpotHedgeBaseMaker.sol/_fillOrderCallback](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol/#L617)
[Vault.sol/__transferCollateralOut](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol/#L343)
[CircuitBreaker.sol/_onTokenOutflow](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/circuitBreaker/CircuitBreaker.sol/#L273)
## Tool used

Manual Review

## Recommendation
Reconsider the withdraw interactions between SpotHedgeBaseMaker and the vault. In a system where only withdrawals can be prevented (due to the usage of CircuitBreaker), while deposits and position openings can continue, requiring a withdrawal in a position opening function is not advisable and can lead to exploits, as described.

**Comment by 42bchen** [comment]
Update:
To simplify matters, without considering the funding design, SpotHedgeMaker is always hedged when opening a position (meaning it will always use 1x leverage). Therefore, when the market crashes, it is hard to liquidate SHBM's position. Meanwhile, if a trader opens a long position on SHBM during a market crash, SHBM can buy the base at a cheaper price, so the base amount of the liquidity provider won't be affected by this assumption. 
I think the probability of not being able to open a long position on SHBM is very low (reverted by the circuit breaker). If opening a short position can be profitable, there will be continuous fund inflow into our vault. When a user opens a short position, SHBM will also deposit funds into the Vault.

Conclusion: The issue is valid, but the probability is low, so we do not plan to address it at the moment. If you believe there are any other important matters that we may have overlooked, please feel free to inform us. Thank you 🙏

**Comment by IllIllI000** [comment]
@42bchen I believe this is also a known issue: `SpotHedgedBaseMaker could trigger CircuitBreaker rate limit when swap/withdraw`. If it's known, can you change to sponsor-disputed, and if it's low, can you add disagree-with-severity? If there are other submissions where you believe they're low, can you also apply the tag there?

**Comment by 42bchen** [comment]
> @42bchen I believe this is also a known issue: `SpotHedgedBaseMaker could trigger CircuitBreaker rate limit when swap/withdraw`. If it's known, can you change to sponsor-disputed, and if it's low, can you add disagree-with-severity? If there are other submissions where you believe they're low, can you also apply the tag there?

already updated it, thank you for point that

**Comment by kosedogus** [comment]
Escalate

I don't think the known issue `SpotHedgedBaseMaker could trigger CircuitBreaker rate limit when swap/withdraw` is accurately representing this issue. It is just pointing out that SHBM could **trigger** CircuitBreaker, so rate limit can start with SHBM swap/withdraw calls, hence it is just mentioning these functions can be initiators for the rate-limit process. But this issue shows what can potentially happen during and after rate-limit process in SHBM.

While I have reviewed the list of known issues and came across aforementioned issue, I didn't thought that known issue implicates this particular issue. I thought it would be "excessive inference" to assume aforementioned known issue also included this. I of course am aware that known issue with its current form doesn't provide much value, hence one can say what I am doing is "insufficient inference", but in the realm of security isn't this what should be done? 

Which one is expected from us, security researchers, I want to ask: 
Saying "well, if the devs are aware that SHBM could trigger CircuitBreaker rate limit, they probably are also aware when the system is rate-limited,regardless of who initiated it, this issue can occur" and assuming it is safe to not submit,
Or because the known issue is not expressive enough, submitting and being sure that they are now aware? 
Therefore, I believe it should be approached with separate consideration.

Other than that,
@42bchen thank you for detailed response :pray:  I can point out some things so that team can decide for the best.
>  I think the probability of not being able to open a long position on SHBM is very low (reverted by the circuit breaker). If opening a short position can be profitable, there will be continuous fund inflow into our vault. When a user opens a short position, SHBM will also deposit funds into the Vault.

Firstly, yes of course rate-limiting is not something that should be expected frequently, but it is something crucial in design of the protocol, and I believe it is important to be ready when that happens. Other than that this situation can occur after rate-limit already started, so that, because new fund inflow into the vault can't stop the rate-limit itself, it won't have any effect. So the possibility of this issue's occurence can be a little higher than assumed I presume.

One other thing that I came across during reviewing other issues is, if I understood correctly the third option in: https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/117#issuecomment-2022041115 can solve both this issue and mentioned issue I believe, because although that issue is different in root cause and impact, both issues benefits from opening excessive short's against SHBM. So instead of reimplementing withdraw interactions between SHBM and vault as I suggested in recommendation, implementing checks before opening position via SHBM as mentioned by @tailingchen might be a good consideration for now or for the future :)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I don't think the known issue `SpotHedgedBaseMaker could trigger CircuitBreaker rate limit when swap/withdraw` is accurately representing this issue. It is just pointing out that SHBM could **trigger** CircuitBreaker, so rate limit can start with SHBM swap/withdraw calls, hence it is just mentioning these functions can be initiators for the rate-limit process. But this issue shows what can potentially happen during and after rate-limit process in SHBM.
> 
> While I have reviewed the list of known issues and came across aforementioned issue, I didn't thought that known issue implicates this particular issue. I thought it would be "excessive inference" to assume aforementioned known issue also included this. I of course am aware that known issue with its current form doesn't provide much value, hence one can say what I am doing is "insufficient inference", but in the realm of security isn't this what should be done? 
> 
> Which one is expected from us, security researchers, I want to ask: 
> Saying "well, if the devs are aware that SHBM could trigger CircuitBreaker rate limit, they probably are also aware when the system is rate-limited, this issue can occur" and assuming it is safe to not submit,
> Or because the known issue is not expressive enough, submitting and being sure that they are now aware? 
> Therefore, I believe it should be approached with separate consideration.
> 
> Other than that,
> @42bchen thank you for detailed response :pray:  I can point out some things so that team can decide for the best.
> >  I think the probability of not being able to open a long position on SHBM is very low (reverted by the circuit breaker). If opening a short position can be profitable, there will be continuous fund inflow into our vault. When a user opens a short position, SHBM will also deposit funds into the Vault.
> 
> Firstly, yes of course rate-limiting is not something that should be expected frequently, but it is something crucial in design of the protocol, and I believe it is important to be ready when that happens. Other than that this situation can occur after rate-limit already started, so that, because new fund inflow into the vault can't stop the rate-limit itself, it won't have any effect. So the possibility of this issue's occurence can be a little higher than assumed I presume.
> 
> One other thing that I came across during reviewing other issues is, if I understood correctly the third option in: https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/117#issuecomment-2022041115 can solve both this issue and mentioned issue I believe, because although that issue is different in root cause and impact, both issues benefits from opening excessive short's against SHBM. So instead of reimplementing withdraw interactions between SHBM and vault as I suggested in recommendation, implementing checks before opening position via SHBM as mentioned by @tailingchen might be a good consideration for now or for the future :)
>  
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by kosedogus** [comment]
@WangSecurity Sir, can you please also check this one? At the time of escalations, I couldn't be able to escalate it because I wasn't using Sherlock since June which corresponds to time where escalations requirements are renewed. I would very much appreciate it if you can check it. Thank you.

**Comment by WangSecurity** [comment]
Will do so a bit later in the next couple of days

**Comment by WangSecurity** [comment]
I agree that this is firstly a known issue. As I understand `SpotHedgedBaseMaker could trigger CircuitBreaker rate limit when swap/withdraw`, it means that if users try to swap/withdraw then they trigger rate limit and cannot perform this operation. I understand that it's not written in the clearest way, but during the contest all watsons have access to sponsors to make sure what answers README mean. Moreover, as the sponsor explains, with short positions, there is a continious fund inflow into the vault. Hence, I believe this report is correctly excluded and should be low/info severity
