### ISSUE TITLE
ihavebigmuscle - Triggering Custom Error Allows Quoter to Return Incorrect Prices

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#132]
ihavebigmuscle

high

# Triggering Custom Error Allows Quoter to Return Incorrect Prices

## Summary
Triggering Custom Error Allows Quoter to Return Incorrect Prices

## Vulnerability Detail
When using `SpotHedgeBaseMaker`, attackers can construct a token that can trigger a custom error under certain circumstances. If this token is added to the path of a uniswap v3 swap, the token can throw a `LibError.QuoteResult` error. This error will directly enter the catch block in the `Quoter` and return any arbitrarily constructed value from the error.

## Impact
By launching the attack, the attacker can cause the `Quoter` to obtain incorrect prices, leading to incorrect results when validating the order off-chain.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/quoter/Quoter.sol#L44-L46

## Tool used

Manual Review

## Recommendation
It is recommended to add extra try/catch for the operation of Uniswap in `SpotHedgeBaseMaker` and throw appropriate errors based on the content of the error.

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  invalid

**Comment by vinta** [comment]
Technically yes, if we add that kind of tokens in the swap path via `SpotHedgeBaseMaker.setUniswapV3Path()`. Though we have no reason to do that, unless the path we set is generated from a untrusted third-party provider and we didn't identity it, or maybe some tokens we trust got hacked and upgraded to adapt this attack.

So valid, but probably won't fix.

**Comment by nevillehuang** [comment]
Since paths can only be set by admin, this issue is invalid.

**Comment by billh-security** [comment]
Escalate

The README clearly states that `SpotHedgeBaseMaker` will not interact with tokens that have 'weird traits.' However, it doesn't provide any security assurances for tokens involved in calls performed by Uniswap's router and pool contracts.
I believe that invalidating this issue merely because swap path is set by the team isn't quite fair. Notably, even a thorough code review for the tokens on a swap path might overlook these vulnerabilities, as the source code could contain infinite custom errors that have the same selector as `QuoteResult` but bear different names—`TransferFailed706627406(uint256,uint256)`, for instance. This poses a risk of the off-chain matching engine incorrectly rejecting or issuing transactions.

The project team has acknowledged the issue as well. Given these factors, I firmly assert that this should be recognized as a valid issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The README clearly states that `SpotHedgeBaseMaker` will not interact with tokens that have 'weird traits.' However, it doesn't provide any security assurances for tokens involved in calls performed by Uniswap's router and pool contracts.
> I believe that invalidating this issue merely because swap path is set by the team isn't quite fair. Notably, even a thorough code review for the tokens on a swap path might overlook these vulnerabilities, as the source code could contain infinite custom errors that have the same selector as `QuoteResult` but bear different names—`TransferFailed706627406(uint256,uint256)`, for instance. This poses a risk of the off-chain matching engine incorrectly rejecting or issuing transactions.
> 
> The project team has acknowledged the issue as well. Given these factors, I firmly assert that this should be recognized as a valid issue.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by billh-security** [comment]
@WangSecurity Could you please take a look at this one when you get a chance? Appreciate it!

**Comment by WangSecurity** [comment]
I agree with the lead judge, this issue relies that a TRUSTED admin will add malicious uniswap path. Hence, should remain invalid.
