### ISSUE TITLE
solmaxis69 - DoS of SpotHedgeBaseMaker.withdraw() if withdrawnBaseAmount exceeds spotBaseBalance

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#21]
solmaxis69

high

# DoS of SpotHedgeBaseMaker.withdraw() if withdrawnBaseAmount exceeds spotBaseBalance

## Summary
In the `SpotHedgeBaseMaker.withdraw()` there is a check whether `withdrawnBaseAmount ` exceeds `spotBaseBalance`. It is used to calculate how many quote tokens the maker needs to withdraw from vault in terms of base tokens. However, the subsequent check of maker's `positionSize` in the vault would dos all calls to `SpotHedgeBaseMaker.withdraw()` where `withdrawnBaseAmount > spotBaseBalance` due to using the wrong operator, `!=` instead of `==`
## Vulnerability Detail
The reason for revert is the following if-statement:
```solidity
if (withdrawnBaseAmount > spotBaseBalance) {
            if (vault.getPositionSize(_getSpotHedgeBaseMakerStorage().marketId, maker) != 0) { //@audit should be equal to zero otherwise reverts
                revert LibError.NotEnoughSpotBaseTokens(withdrawnBaseAmount, spotBaseBalance);
            } else {
            ...
```
Whenever a maker fills order, it deposits acquired quote tokens from swapping base tokens into vault and transfers them into margin account. This is almost always means that maker's `positionSize` would not be equal to zero, since `fillOrder()` function is a part of `ClearingHouse._openPosition()` which in result settles position for both maker and taker and changes their `positionSize`. This effectively means that any amount that exceeds the spot balance is not withdrawable and the maker's quote tokens would be stuck in the vault unless someone opens a position against a maker with a `isBaseToQuote == false`.
## Impact
DoS
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L331-L334
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol#L416-L435

## Tool used

Manual Review

## Recommendation
Change the `!=` to `==`:
```solidity
if (vault.getPositionSize(_getSpotHedgeBaseMakerStorage().marketId, maker) == 0) { 
                revert LibError.NotEnoughSpotBaseTokens(withdrawnBaseAmount, spotBaseBalance);
```

**Comment by lnxrp** [comment]
- Valid but won't fix
- Known issue
- We don't allow quote token withdrawal when the maker has position because we intend for the maker to maintain roughly 100% margin ratio at all times. Ideally, should the maker to withdraw quote token, it must also reduce position at the same time so that margin ratio stay at 100%; however we haven't implement such logic yet
- Currently maker LP are trusted & whitelisted. LP must accept the potential illiquidity scenario before he can deposit

**Comment by IllIllI000** [comment]
@lnxrp shouldn't this be Sponsor Disputed? It's working as designed for the contest, and how I understood it to work when I was reviewing the code. It's also one of the known issues: `LP deposit and withdrawal of OracleMaker and SpotHedgeBaseMaker is designed to simplify asset transfer in the majority of the cases; however, it is not guaranteed in edge cases when the collateral is low (or when the utilization is high)`

**Comment by lnxrp** [comment]
@IllIllI000 Yes but I may have misunderstood Sponsor Confirmed's meaning. I was meant to "confirm" that the reported issue is possible. However, since under our current system setup (maker LP are trusted & whitelisted) the issue wouldn't harm even if it happens, so we won't fix it at least for now.

Should I change it to "Sponsor Disputed"? 

Updated: nvm we have changed it
