### ISSUE TITLE
nuthan2x - Oracle can return different prices in same transaction

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-perpetual-judging#31]
nuthan2x

high

# Oracle can return different prices in same transaction

## Summary
This issue is inspired from [Flat-money perp dex](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/216).

The issue there is medium beacuse of only one token using pyth. And the instrument is not exotic, but perp here will list exotics like fx/metals which have high volatility within a single block due to news trading startegy.

The Pyth network oracle contract allows to submit and read two different prices in the same transaction. This can be used to create arbitrage opportunities that can make a profit with no risk at the expense of users on the other side of the trade.

## Vulnerability Detail

PythOracleAdapter.sol uses `Pyth` network as the primary source of price feeds. This oracle works in the following way:

A dedicated network keeps track of the latest price consensus, together with the timestamp.
This data is queried off-chain and submitted to the on-chain oracle.
It is checked that the data submitted is valid and the new price data is stored.
New requests for the latest price will now return the data submitted until a more recent price is submitted.
One thing to note is that the Pyth network is constantly updating the latest price (every 400ms), so when a new price is submitted on-chain it is not necessary that the price is the latest one. Otherwise, the process of querying the data off-chain, building the transaction, and submitting it on-chain would be required to be done with a latency of less than 400ms, which is not feasible. This makes it possible to submit two different prices in the same transaction and, thus, fetch two different prices in the same transaction.

This can be used to create some arbitrage opportunities that can make a profit with no risk.

- Create a small leverage position.
- Announce an adjustment order to increase the size of the position by some amount.
- In the same block, announce a limit close order.
- After the minimum execution time has elapsed, retrieve two prices from the Pyth oracle where the second price is higher than the first one.
- Execute the adjustment order sending the first price.
- Execute the limit close order sending the second price.

**Pyth network multiple submissions**

We can find proof that it is possible to submit and read two different prices in the same transaction here. In this transaction updatePriceFeeds is called with two different prices. After each call the current price is fetched and an event is emitted with the price and timestamp received. As we can see, the values fetched are different for each query of the price.

```js
Address 0x8250f4af4b972684f7b336503e2d6dfedeb1487a
Name    PriceFeedUpdate (index_topic_1 bytes32 id, uint64 publishTime, int64 price, uint64 conf)
Topics  0 0xd06a6b7f4918494b3719217d1802786c1f5112a6c1d88fe2cfec00b4584f6aec
        1 FF61491A931112DDF1BD8147CD1B641375F79F5825126D665480874634FD0ACE
Data    publishTime: 1706358779
        price: 226646416525
        conf: 115941591

Address 0xbf668dadb9cb8934468fcba6103fb42bb50f31ec
Topics  0 0x734558db0ee3a7f77fb28b877f9d617525904e6dad1559f727ec93aa06370866
Data    226646416525
        1706358779

Address 0x8250f4af4b972684f7b336503e2d6dfedeb1487a
Name    PriceFeedUpdate (index_topic_1 bytes32 id, uint64 publishTime, int64 price, uint64 conf)View Source
Topics  0 0xd06a6b7f4918494b3719217d1802786c1f5112a6c1d88fe2cfec00b4584f6aec
        1 FF61491A931112DDF1BD8147CD1B641375F79F5825126D665480874634FD0ACE
Data    publishTime: 1706358790
        price: 226649088828
        conf: 119840116

Address 0xbf668dadb9cb8934468fcba6103fb42bb50f31ec
Topics  0 0x734558db0ee3a7f77fb28b877f9d617525904e6dad1559f727ec93aa06370866
Data    226649088828
        1706358790
```

## Impact

Different oracle prices can be fetched in the same transaction, which can be used to create arbitrage opportunities that can make a profit with no risk at the expense of users on the other side of the trade.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L63

https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L83

## Tool used

Manual Review

## Recommendation

```diff
File: PythOracleAdapter.sol
contract PythOracleAdapter is IPythOracleAdapter, Ownable2Step {
    IPyth internal _pyth;
    uint256 internal _maxPriceAge;
+   uint256 public lastOffchainUpdate;

    (...)

    function updatePrice(bytes32 priceFeedId, bytes memory signedData) external { 
+       if (lastOffchainUpdate >= block.timestamp) return;
+       lastOffchainUpdate = block.timestamp;

        if (!priceFeedExists(priceFeedId)) revert LibError.IllegalPriceFeed(priceFeedId);

        (...)
    }

    (...)

}

```

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  its expected to provide accurate data

**Comment by 0xvj** [comment]
Escalate
The attack path of the actual issue demonstrates how attacker can use different prices returned by the pyth oracle in the same transaction to extract value from OracleMaker by depositing and withdrawing  to get instant arbitrage opportunity.

But as the attack path mentioned by warden uses opening and closing position which wouldn't work due to delay(opening and closing cannot be executed in the same tx as trades are executed by relayer)

> In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

As this issue identifies the root cause but doesn't describe the attack path, this should be low as mentioned in the sherlock docs.

**Comment by sherlock-admin2** [comment]
> Escalate
> The attack path of the actual issue demonstrates how attacker can use different prices returned by the pyth oracle in the same transaction to extract value from OracleMaker by depositing and withdrawing  to get instant arbitrage opportunity.
> 
> But as the attack path mentioned by warden uses opening and closing position which wouldn't work due to delay(opening and closing cannot be executed in the same tx as trades are executed by relayer)
> 
> > In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.
> 
> As this issue identifies the root cause but doesn't describe the attack path, this should be low as mentioned in the sherlock docs.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nuthan2x** [comment]
refer to comments https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/38#issuecomment-2041526954, https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/32#issuecomment-2042012229

Escalator says `opening and closing cannot be executed in the same tx` can be bypassed, you don't need to open and close position in one transaction, You can time it with relayer as mentioned at  https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/38#issuecomment-2041526954, but still, you can do arbitrage  in multiple blocks in a window of 10 - 50 seconds because of pyth max age allows till 60 seconds.
 
 
My issue above didn't explain all this flow because its directly inspired from [flat-perp-dex](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/216).  And that issue clearly explained with POC, and their escalation comments proved it.

You can open position via both 
 - order gateways v1  by create order then execute order, and 
 - use relayer powered order gateway2's settle order.

So, first  by create order via ordergateway v1 to close a position
then after delay, open position via gateway v2 via relayer
relayer will settle at price A
then backrun it with update price
then in a  block after the price update, trigger ordergateway v1.execute close order
profit the price difference in both long/short.

so its possible to do arbitrage via open/close positions also. Other multiple strategies are also possible with limit/market orders with both gateways.

**Comment by nevillehuang** [comment]
I think the original issue did not do a good job in describing protocol specific logic of how this issue can be exploited as noted in #123. So I believe invalidation is appropriate, if the following comment [here is true](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/131#issuecomment-2044294489)? If the attack vector isn't well described I am inclined with agreeing to invalidating the issue, especially so if the delay of opening and closing positions is true.

**Comment by nevillehuang** [comment]
I believe this issue is invalid because it is not sufficiently described and doesn't directly correlate to perpetual protocol in general and instead seems to be a direct copy of the previous issue. There is no announcing of orders here and the workings of perpetual and flatmoney is inherently different. Any additional information provided within escalation should not be considered as a add-on to address this.

**Comment by WangSecurity** [comment]
Agree with the reasons laid out above by the Lead Judge and the escalator. This report is indeed insufficient and the duplication rule mentioned in escalation should be applied here.

Planning to accept the escalation and invalidate this report.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xvj](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/31/#issuecomment-2041329061): accepted
