### ISSUE TITLE
nuthan2x - Arbitrage opputinities due to huge max age and lack of updating pyth price on every order execution by relayer/makers.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#32]
nuthan2x

high

# Arbitrage opputinities due to huge max age and lack of updating pyth price on every order execution by relayer/makers.

## Summary

Arbitrage opputinities due to huge max age and lack of updating pyth price on every order execution by relayer/makers.

## Vulnerability Detail

The oracle (pyth) checks if current price is not so stale by checking maxAge state. But it is hardcoded to 60 inside contructor. Even though admin has power to update them whenever needed, that age can be leveraged for arbitrage.

Since perpetual has 60 as max age initially, the users can drain the LP by arbitrage on occasions of news trading the metals/exotic forex instruments. Or the incident like latest Uniswap 60% pump in < 1 min can be arbitraged for profit. 
Also if minimum price age after update should be > 0, so any price update on this block can be used on next block only, but perpetual allows using current update price to be used for orders of current block, and this allows arbitrage.

Due to following reasons,

1. using same age for all price feed/instruments
2. Not updating prices on each action related to vault.
3. There's no minimum age, meaning the latest price can be used in the latest block itself

Look at `cap.io` perp dex that relies on pyth oracles like  `perpetual`, they have minimum/maximum ages per each price feed.

proof ==> look at line 20 at [MarketStore.sol](https://arbiscan.io/address/0x328416146a3caa51BfD3f3e25C6F08784f03E276#code#F1#L20)

![image-1](https://github.com/sherlock-audit/2024-02-perpetual-nuthan2x/assets/92864243/26bae07e-bb5c-48a5-af12-8cee13eeca93)

And they update pyth price on each order execution. proof ==> look at line 133 of [Processor.sol](https://arbiscan.deth.net/address/0xf7D5E17b430bF1e8B55B3675E5c216e6Abc4fA39)

![image](https://github.com/sherlock-audit/2024-02-perpetual-nuthan2x/assets/92864243/447270ae-eab6-4380-8b24-5fc71b4d6884)

## Impact
Arbitrage opputinities due to huge max age and lack of updating pyth price on every order execution by relayer/makers.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L51-L64

## Tool used

Manual Review

## Recommendation

1. Implement minimum age / max age per each market/instrument. Minimum age to be > 0 always. 
2. Update price on each action that involves moving $$ on vault.
3. And remove the 60 as max age, or set them in the constructor argument.

**Comment by 0xvj** [comment]
Escalate

The attack path of the actual issue demonstrates how attacker can use different prices returned by the pyth oracle in the same transaction to extract value from OracleMaker by depositing and withdrawing  to get instant arbitrage opportunity.

Even if the root cause is clear that attacker can submit two Pyth prices in same tx, warden has failed to specify how an attacker can use this to create arbitrage in the perp contracts.

>In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

As this issue identifies the root cause but doesn't clearly describe the impact or attack path, this should be low as mentioned in the Sherlock docs.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The attack path of the actual issue demonstrates how attacker can use different prices returned by the pyth oracle in the same transaction to extract value from OracleMaker by depositing and withdrawing  to get instant arbitrage opportunity.
> 
> Even if the root cause is clear that attacker can submit two Pyth prices in same tx, warden has failed to specify how an attacker can use this to create arbitrage in the perp contracts.
> 
> >In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.
> 
> As this issue identifies the root cause but doesn't clearly describe the impact or attack path, this should be low as mentioned in the Sherlock docs.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nuthan2x** [comment]
Sherlock docs says  `- In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.`

Escalator says this issue doesn't clearly describe the impact or attack path, so it should be low.

But, It explains both impact and attack clearly.

**Impact** : 

- Look at the end of Line 3 of `Vulnerability Detail`  saying `the users can drain the LP by arbitrage on occasions of news trading the metals/exotic forex instruments. Or the incident like latest Uniswap 60% pump in < 1 min can be arbitraged for profit.`
- Look at the end of Line 4 of `Vulnerability Detail` . It says `arbitraged for profit`. Arbitraging means making $ out of price difference, `profit` word is also mentioned.   
- The impact is saying that LP can be drained.  How more detailed or clear should the impact be ? 
- The judge understood the impact clearly.  Making money of arbitraging means LP drained. The impact is clear.

**Attack Path** : 
- Again,  Look at the end of Line 4 of `Vulnerability Detail` . It says `arbitraged for profit`. The word arbitrage means buy at price 1 and sell at price 1.1 making 10% profit.  Everyone knows it.        
- This issue is not some complex re-entrancy attack, to point exact flow of function calls. Its arbitrage. Buy then sell. Open then close. The word arbitrage itself explains the attack path.


If this issue just mentioned the root cause alone, then its a low issue. But the issue clearly states that LP can be drained. And the word `Arbitrage` is  mentioned, which is the attack path. So its a valid issue.

**Comment by nevillehuang** [comment]
@nuthan2x Could you verify the comment [here as well](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/131#issuecomment-2044294489)? If the attack vector isn't well described I am inclined with agreeing to invalidating the issue, especially so if the delay of opening and closing positions is true.

**Comment by nuthan2x** [comment]
@nevillehuang, @IllIllI000 I believe this issue is unique  because of different root causes. And the fix done in #123 saying to allow LP deposits/withdrawals by relayers cannot solve the arbitrage bug this issue states. so this is not dup of #123, I have submitted #31 as 123's dup. 

The root cause of #123 is possibility of different pyth price update in same block. But this issue talks about pyth price not being updating on every open/close/create/execute orders. I have also mentioned that max age being 60 is huge, cap.io/kwenta perp dex sets it at 30 and they update price at every trading action done with the system. (look at the images above).

Even if admin sets it to 30, you can still arbitrage the 30 sec price diff when news trading like uni gov update/ in forex markets.

The right fix for this issue is  when keeper/relayer calls `ordergateway.execute` and o`rdergatewayV2.settleOrder`, just call an internal pyth.updatePrice. 

Exact attack path, min 3 sec day as said  here https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/orderGateway/OrderGateway.sol#L25

Exact attack path, 
1. create open order
2. after 3 sec delay, execute order yourself at current 3500$/ETH pyth price
3. after 20 seconds, create close order
4. execute close order yourself, but before that update the price to 3550$/ETH and then execute and profit off. We are still in < 30 seconds time frame.

Since #123 fix doesn't solve this issue, 
The recommendation is to do like cap.io/kwenta dex, that is to update pyth price on every trading action.
Or 
create a keeper fee incentive like kwenta.

**Comment by IllIllI000** [comment]
The readme itself says `OrderGatewayV2’s relayer may not postpone order enough for mitigating others front-run oracle if the maker is OracleMaker`, so anything to do with trying to predict the OracleMaker's trade price is invalid

**Comment by nuthan2x** [comment]
> The readme itself says `OrderGatewayV2’s relayer may not postpone order enough for mitigating others front-run oracle if the maker is OracleMaker`, so anything to do with trying to predict the OracleMaker's trade price is invalid

It not about predicting price. Its about using stale price and we don't update price on every action. The issue of frontrunning solved by synthetix x kwenta x cap is by making delayed orders  + when executing ( they update pyth price along execute). But in  perpetual here, only order delay is implemented .

Consider the difference of implementation here, max age is 60
T1 = 1 & price =  3500
T2 = 29 & price = 3525 in cex

but pyth price is not updated by anyone because its a low volatile trading session like Japan session
so now perpetual team reads the price of stale 3500 when opening position. Imagine when opening position, we also update the price along execution so we can read the 3525 and open, just like how kwenta/snx and cap.io is doing ? look at [example transaction](https://optimistic.etherscan.io/tx/0xfe4a97797c7aa264a96d8fd7ee6ee38f5b63100a9f8bc6d76f5d4e191ab5a791) , [update price call on order execution](https://app.blocksec.com/explorer/tx/optimism/0xfe4a97797c7aa264a96d8fd7ee6ee38f5b63100a9f8bc6d76f5d4e191ab5a791?line=9&debugLine=9) and  above cap.io images.

The profit of the stale price is the prize. You don't have to rely on relayer with v2 gateway, you can create + execute order yourself with delay on gateway v1 to make $ out of this issue.

**Comment by 0xvj** [comment]
> Exact attack path, min 3 sec day as said here https://github.com/sherlock-audit/2024-02-perpetual/blob/d39d7be735a3df01fb958542f9473cc5b80af956/perp-contract-v3/src/orderGateway/OrderGateway.sol#L25
> 
> Exact attack path,
> 
> 1. create open order
> 2. after 3 sec delay, execute order yourself at current 3500$/ETH pyth price
> 3. after 20 seconds, create close order
> 4. execute close order yourself, but before that update the price to 3550$/ETH and then execute and profit off. We are still in < 30 seconds time frame.

@nuthan2x  FYI ordergateway.sol is not in the scope. And sponsor mentioned that ordergateway v1 will not be deployed in production. So this attack vector is not valid. 

You can check the sponsor message [here](https://discord.com/channels/812037309376495636/1211689150663622707/1217136627122573403)

**Comment by nevillehuang** [comment]
I agree with the discussions highlighted [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/32#issuecomment-2041384808) and [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/32#issuecomment-2045249857) within the issue, this issue should be invalid.

**Comment by WangSecurity** [comment]
I also agree with the points raised by the escalator. The duplication rule highlighted in the escalation should indeed be applied here.

Planning to accept the escalation and invalidate the issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xvj](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/32/#issuecomment-2041384808): accepted
