### ISSUE TITLE
enfrasico - Loss of gas yield for protocol across all contracts deployed on Blast

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#50]
enfrasico

high

# Loss of gas yield for protocol across all contracts deployed on Blast

## Summary
Based on the protocol provided context, perpetual is intended to be deployed on Optimism/Blast.

Blast has the unique implementation of directing sequencer fees to contracts that uses fees. Default gas mode for all contracts is VOID. This means that none of the accumulated sequencer gas yield will be shared with these contracts regardless of the amount of usage. In order for contracts to partake in this revenue sharing model, they will need to interact with Blast precompile at `0x4300000000000000000000000000000000000002` to change their gas mode.  

## Vulnerability Detail
Because perpetual protocol does not have any way to set its gas mode, it is unable to accrue any yield generated from users interacting with their contracts.

## Impact
Massive loss on gas yield across all contracts deployed on Blast.

## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/vault/Vault.sol#L27

## Tool used

Manual Review

## Recommendation
Add Blast wrappers to the current contracts so that gas mode can be set and gas yields can be claimed.

**Comment by nevillehuang** [comment]
Invalid, out of scope. Any contracts catering to blast is not developed yet and should not be assumed to be not catered

**Comment by vinta** [comment]
Since we did mention we might deploy to Blast and we indeed forgot to list it as known issue that we haven't yet started to do any Blast-related developments.

So I think this one is valid, but probably won't fix until we're going to deploy on Blast.

**Comment by nevillehuang** [comment]
Since no information was present in contest details about claiming gas, I believe this to be out of scope given such yield claims are not required for the functioning of the protocol on blast. Nowhere in the codebase/documentation was it highlighted that claiming blast yields is a necessary core logic of the perpetual protocol.

> 14. Loss of airdrops or liquidity fees or any other rewards that are not part of the original protocol design is not considered a valid high/medium.

**Comment by Coareal** [comment]
Escalate

#51, #52 are Blast related issues that are functionally different and should not be duped to this issue. They are all distinct issues. We should not confuse a class of issues (reentrancy, L2, integer overflow etc) all as dupes of each other.

It is explicitly mentioned on the contest front page that the protocol is going to be deployed on Blast. It would be absolutely unfair for researchers who have spent time digging into issues relating to Blast to be made invalid.

Claiming gas yield is inherent to Blast. Any protocol deployed on Blast should be expected to be able to handle Blast related peculiarities unless explicitly mentioned to be out of scope. For example, a protocol that integrates with LIDO, should be able to handle rebase up/down of stETH. Frontrunning issues on OP/Base/Arbitrum L2 are not considered valid due to the FIFO sequencer. These are all features of the respective integrations.

The default yield mode for Gas yield is VOID. Protocol being unable to alter and collect such yields **IS** a vulnerability. This is vastly different from "airdrops" when gas yield **IS** a feature of Blast.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> #51, #52 are Blast related issues that are functionally different and should not be duped to this issue. They are all distinct issues. We should not confuse a class of issues (reentrancy, L2, integer overflow etc) all as dupes of each other.
> 
> It is explicitly mentioned on the contest front page that the protocol is going to be deployed on Blast. It would be absolutely unfair for researchers who have spent time digging into issues relating to Blast to be made invalid.
> 
> Claiming gas yield is inherent to Blast. Any protocol deployed on Blast should be expected to be able to handle Blast related peculiarities unless explicitly mentioned to be out of scope. For example, a protocol that integrates with LIDO, should be able to handle rebase up/down of stETH. Frontrunning issues on OP/Base/Arbitrum L2 are not considered valid due to the FIFO sequencer. These are all features of the respective integrations.
> 
> The default yield mode for Gas yield is VOID. Protocol being unable to alter and collect such yields **IS** a vulnerability. This is vastly different from "airdrops" when gas yield **IS** a feature of Blast.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I believe head of judging opinion supports my stance as seen [here](https://discord.com/channels/812037309376495636/1013592891773419520/1225758233625366569). I believe one reason for not including yield claim could be bytecode limit.

**Comment by Czar102** [comment]
It is a valid design choice not to gather this optional revenue. Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Agree with the comment above. Moreover, I believe this should be classified as an opportunity loss with no core functionality break. Hence, planning to reject the escalation and keep the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/50/#issuecomment-2037115009): rejected
