### ISSUE TITLE
santipu_ - Protocol fees will increase bad debt when liquidating underwater positions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#64]
santipu_

high

# Protocol fees will increase bad debt when liquidating underwater positions

## Summary

When a position is liquidated with a tight margin or a negative margin, the protocol fee sent to `ClearingHouse` will increase bad debt on the protocol and will prevent other users from realizing their profits. 

## Vulnerability Detail

When a position is liquidated, a portion of the trader's margin will be sent to the liquidator and to the protocol, it will happen at `ClearingHouse.liquidate`.

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L193-L194
```solidity
vault.transferMargin(params.marketId, params.trader, liquidator, result.feeToLiquidator);
vault.transferMargin(params.marketId, params.trader, address(this), result.feeToProtocol);
```

The fee sent to the liquidator is crucial for rewarding on-time liquidations and keeping the protocol healthy, however, the fee sent to the protocol doesn't have a purpose and it will sit there without moving. 

The issue is that when a liquidation generates some bad debt, meaning the trader doesn't have enough margin to pay the liquidation fees, the fee to the protocol will increase the bad debt. In this scenario, is possible that the PnL pool is emptied by this fee, preventing other users from realizing their profits and withdrawing them. 

The README states the following in the "known issues" section:

> ClearingHouse may has some surplus margin (from liquidation fee) that can not be withdrawn by anyone yet

The protocol acknowledges that the protocol fee on liquidations doesn't have a purpose at now. Therefore, why collect the protocol fee in scenarios where it could increment the bad debt on the protocol, preventing other users from realizing their profits?

## Impact

When a position is liquidated with a tight margin or a negative margin, the protocol fee will increase the bad debt on the protocol, preventing other users from realizing their profits.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L194

## Tool used

Manual Review

## Recommendation

To mitigate this issue is recommended to implement a check that won't collect the protocol fee when the trader's margin doesn't have enough funds to pay it. Otherwise, the protocol fee will cause more bad debt to the protocol without justification, because that fee doesn't serve a purpose.

Duplicate of #106

**Comment by sherlock-admin3** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  same as 063

**Comment by santipu03** [comment]
Escalate

I believe this issue is not a duplicate of #106 and should be a valid HIGH.

Issue #106 describes that when bad debt is generated, it may cause a bank run because bad debt is not correctly handled by the protocol. However, even though I agree with the point made by issue #106, my issue is pointing out a different problem within the bad debt scenario. 

The core of my report is the following, **when a position is liquidated with bad debt, the protocol fees will INCREASE the bad debt on the protocol**, further worsening the situation. 

Given that the protocol fees don't have any use by now, they shouldn't be collected when bad debt is generated because that will take more tokens out from the PnL pool, increasing the bad debt. 

Reading the Sherlock's rules for categorizing a HIGH issue, I'd agree that this issue falls into that category:

> IV. How to identify a high issue:
> 1. Definite loss of funds without (extensive) limitations of external conditions.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe this issue is not a duplicate of #106 and should be a valid HIGH.
> 
> Issue #106 describes that when bad debt is generated, it may cause a bank run because bad debt is not correctly handled by the protocol. However, even though I agree with the point made by issue #106, my issue is pointing out a different problem within the bad debt scenario. 
> 
> The core of my report is the following, **when a position is liquidated with bad debt, the protocol fees will INCREASE the bad debt on the protocol**, further worsening the situation. 
> 
> Given that the protocol fees don't have any use by now, they shouldn't be collected when bad debt is generated because that will take more tokens out from the PnL pool, increasing the bad debt. 
> 
> Reading the Sherlock's rules for categorizing a HIGH issue, I'd agree that this issue falls into that category:
> 
> > IV. How to identify a high issue:
> > 1. Definite loss of funds without (extensive) limitations of external conditions.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oot2k** [comment]
I think this issue should be duped with 106 following sherlocks duplication rule.
This report points out a higher impact like the escalation mentions, which means it should be considered valid.
Our report (106) points out a less severe impact, the root cause is the same: wrong handling of bad debt.

**Comment by nevillehuang** [comment]
@paco0x @lnxrp Could you look into the impact of this? To me this seems to be a known issue as noted in comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/106#issuecomment-2022253820).

**Comment by paco0x** [comment]
> @paco0x @lnxrp Could you look into the impact of this? To me this seems to be a known issue as noted in comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/106#issuecomment-2022253820).

I agree, we're aware of this issue, the possibility of insolvency of the pnl pool is known and a design choice.

**Comment by santipu03** [comment]
I will state here something similar to what I've already said in issue #65.

Even though the protocol docs state that the PnL pool insolvency may be a known issue, it's not stated in the contest README and thus the Sherlock rules for valid issues have more importance when considering the validity of this issue. That's why I escalated this issue and I think it's a valid issue.

**Comment by nevillehuang** [comment]
@santipu03 Unless I have misinterpreted sherlocks rule, I believe this issue and #106 to be invalid due to known [documentation comments](https://perp.notion.site/PnL-Pool-d245ccab1b184a1d87a83b7f43dda86d) indicating so.

> If the PnL Pool is empty, a trader could no longer be able to settle profit because there is no funds in the Pool to pay him. The trader will have to wait until someone settled their loss and the pool is refilled

**Comment by WangSecurity** [comment]
Do I understand correctly, that the point of the report is that taking protocol fees from liquidation takes to many funds from PnL pool, which leads to the pool being empty? And the fees are not used anywhere, hence your mitigation is to not take them from liquidating the insolvent positions (by insolvent I mean the user's loss is greater than their margin)? @santipu03

**Comment by santipu03** [comment]
That's correct.

**Comment by WangSecurity** [comment]
I believe this should remain invalid since it's an intended design and the known issue about empty pool should be applied here. I see that the README and the issue regarding empty PnL pool do not explicitly mention this scenario, but it still applies here, since empty PnL pool is intended this way.

Planning to reject the escalation and leave the issue as it is.

**Comment by santipu03** [comment]
Check my comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/65#issuecomment-2070282670). 

This issue falls under the same category as #65, #133, #126 and #127, where there is not a bug in the implementation but a flawed design that causes a loss of funds.

**Comment by WangSecurity** [comment]
I've read your comment, I see that #133, #126 and #127 are taking intended design into consideration. But the problem with this report is that empty PnL pool is a known issue based on README, moreover, the solution in a form of "buffer balance" proposed by the team will mitigate this issue. Hence, my decision remains the same: reject the escalation and leave the issue as it is.

**Comment by santipu03** [comment]
If we consider that the PnL being empty is a known issue, submissions like #102 or #115 regarding bad debt should also be invalid because, in the end, the bad debt impacts users when the PnL pool is empty, right?

**Comment by Oot2k** [comment]
Have to agree with santipu here. Root cause of 102 is that in case there is bad dept, (no matter where it comes from) will prevent position closes. This is similar to this issue and 106.
So it should be judged accordingly.

**Comment by etherSky111** [comment]
Hey guys, I understand your point to make your issues as valid.
However, please try to be fair.
#102 and your issues are totally different issues.
And please check the comments from sponsor team on these issues.
The impact of #102 is really high and the likelihood is also high.
The sponsor team decided to disable funding fee at this point due to they didn't find suitable solution.
I still insist that the #102 should be high but decided to respect judge's decision.

**Comment by WangSecurity** [comment]
I disagree that the validity and severity of issues #102 and #115 have any effect on this report and vice versa. The root cause and the impact are very different. i don't see that bad debt is the root cause for 102 or 115 and to me they look valid even without the bad debt aspect.

I believe this report has to remain invalid, since empty PnL pool is known issue and this report is to prevent taking protocol fees if it's empty. I agree that it would be better to actually not take those fees, but I have to reject the escalation and leave the issue as it is under the fact of insolvency of the pnl pool is known and a design choice.

**Comment by santipu03** [comment]
@WangSecurity 
Let me explain:
For example, the impact on issue #115 is that the attacker will have positions that cannot get liquidated. Therefore, if price movements make those positions liquidatable, they won't get liquidated, causing bad debt on the protocol. 

In the Perpetual protocol, the only impact that bad debt has is just emptying the PnL pool too much. Therefore, when all users try to withdraw, if some bad debt has been generated in the way, the last users won't be able to withdraw their assets due to the PnL pool being empty. This is the only impact of the bad debt, when the PnL pool is empty.

That's why I said that the bad debt essentially affects users when the PnL is empty. And that leads me to my statement from before: If the PnL being empty is a known issue, all issues whose impacts are the creation of bad debt (that ultimately is the empty PnL pool) should also get invalidated like this one. 

I really think that the PnL pool being empty cannot be considered a known issue just because of a couple of vague statements on the docs like these ones:
> PnL Pool currently starts empty, so a trader with realized gains may experience temporary illiquidity when he tries to withdraw those gains. This inconvenience will be mitigated in the future with a buffer balance

> If the PnL Pool is empty, a trader could no longer be able to settle profit because there is no funds in the Pool to pay him. The trader will have to wait until someone settled their loss and the pool is refilled

**Comment by WangSecurity** [comment]
The problem of issue #115 is that liquidating small positions will not get any rewards to liquidators. Not due to PnL pool being empty, but due to the rounding down, which leads to the possibility of opening lots of small trades (which results in holding one big) without fear of liquidation. My judgement for both #102 and #115 was not based on the aspect of empty PnL pool, hence they're left valid. But for this issue the problem is that taking protocol fee will still empty the PnL pool, which is known issue that insolvency of PnL pool may occur.

**Comment by santipu03** [comment]
But the possibility of opening lots of small trades (which results in holding one big) without fear of liquidation is not an impact per se. When the positions have to be liquidated but they don't, bad debt is created, and it lastly impacts users when the PnL pool is empty. 

To be clear, issue 115 will have a real impact ONLY when the PnL pool is empty. If not, that issue will never impact either the protocol or its users. That's why I was saying that the impact of issue 115 (and all other issues that cause bad debt) will depend on wether the PnL pool becomes empty or not.

**Comment by WangSecurity** [comment]
As I've said earlier, my judgement on the 2 issues mentioned above, wasn't based on the fact of empty PnL pool. For them, PnL pool is not a root cause and there are other impacts besided empting the PnL Pool, that is why I decided to keep them valid. 

Simply put, as I've said above, 102 and 115 are still valid if we apply the known issue regarding empty PnL Pool.

**Comment by santipu03** [comment]
In this issue, the empty PnL pool is also not the root cause. The issue simply describes that when a position underwater is liquidated, that protocol fee will enlarge the bad debt on the protocol. I only mentioned the PnL pool because it's the factor that will cause the greater impact on the users (as well as issue 115).

**Comment by WangSecurity** [comment]
But my judgement regarding 115 is based on the fact that users may open positions without the fear of liquidation. Therefore, they can open large positions (separated in lots of small ones) and avoid risk of liquidation. If their position firstly after opening a trade goes into liquidatable state, they are not liquidated and then their position goes back in profit. Therefore, I think it's a some sort of free-risk trade. Hence, it is valid not because it causes a bad debt and empty PnL pool.

**Comment by santipu03** [comment]
The main reason I escalated this issue is because I thought that the Sherlock rules had more validity than the NatSpec and the documentation. This issue is similar to #65 where some vague statements on the docs define that something is a "known issue", regardless of the root cause, the impact, or the mitigation.

If you already decided that the empty PnL pool is a "known issue" regardless of the scenario, the cause, the mitigation, or the impact, then I have no more to say. Just one thing, that I agree with you that the Sherlock docs need an update. 

P.S. I'd really appreciate it if @Evert0x could state his opinion about this issue as a final confirmation.

**Comment by Evert0x** [comment]
@WangSecurity is correct that this "empty PnL pool" is a know issue. This issue is only relevant if the PnL is (close to) empty. This should should stay invalid

**Comment by Oot2k** [comment]
I just want to add here that the known issue is:

"PnL Pool currently starts empty, so a trader with realized gains may experience temporary illiquidity when he tries to withdraw those gains. This inconvenience will be mitigated in the future with a buffer balance"

-> even a buffer balance wont fix this issue, bad dept can be larger then the balance, especially because it states "STARTS EMPTY"

For this reason I still believe that 106 and 64 (this issue) are valid.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #106

---

Even if we don't treat this as a known issue, which I think it is. I believe it's a design choice.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/64/#issuecomment-2037778092): rejected
