### ISSUE TITLE
santipu_ - Inability to liquidate whitelisted makers will cause bad debt on the protocol

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#65]
santipu_

high

# Inability to liquidate whitelisted makers will cause bad debt on the protocol

## Summary

Whitelisted makers like `OracleMaker` and `SpotHedgeBaseMaker` are not liquidatable, and this may create bad debt for the protocol in case the market moves aggressively against their positions. 

## Vulnerability Detail

Whitelisted makers like `OracleMaker` and `SpotHedgeBaseMaker` are currently not liquidatable and that may cause the creation of bad debt for the protocol. Here is the check that prevents the liquidation of whitelisted makers:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L166-L168
```solidity
    if (_isWhitelistedMaker(params.marketId, params.trader)) {
        revert LibError.CannotLiquidateWhitelistedMaker();
    }
```

Now, let's see in what scenarios could the whitelisted makers need to be liquidated to prevent bad debt. We'll start with **`OracleMaker`**.

`OracleMaker` has a fairly simple mechanism, users can deposit collateral tokens into the maker and those will be deposited in the Vault as a margin for the maker. When a trader wants to open a position against `OracleMaker`, the maker will take the opposite position, opening or closing positions as necessary. 

Depending on the market sentiment, is possible that traders mostly open positions to one side (short or long), therefore the maker will take the opposite direction. In these cases, when the market is volatile and moves aggressively against the maker's position, is possible that LPs start withdrawing liquidity from the maker to avoid losses. In that scenario, if the market continues to move against the `OracleMaker`'s position, the deposited margin won't be enough to cover for the realized losses, therefore creating bad debt on the protocol.

Now let's see how can **`SpotHedgeBaseMaker`** generate bad debt:

In `SpotHedgeBaseMaker`, the mechanism is a little different because LPs deposit base tokens (e.g., ETH) in the maker. When a trader wants to open a short position against the `SpotHedgeBaseMaker`, the maker will take the opposite direction (i.e., long) and will hedge that position by swapping base tokens for collateral tokens and depositing them into the Vault as a margin.

Now, when `SpotHedgeBaseMaker` has a long position and the market starts falling quickly, LPs are going to start withdrawing liquidity from the maker, therefore withdrawing margin from the maker's position. In that scenario, if the market continues to move against the maker and no positions are closed against that maker, it will arrive at a point where the deposited margin is not enough to cover for all losses, creating bad debt on the protocol.

## Impact

When the market aggressively moves against `OracleMaker` and `SpotHedgeBaseMaker`, it will arrive at a point where the deposited margin is not enough to cover the unrealized losses, creating bad debt for the protocol because they can't be liquidated. 

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L166-L168

## Tool used

Manual Review

## Recommendation

It's recommended to allow liquidations against `OracleMaker` and `SpotHedgeBaseMaker` to prevent the creation of bad debt for the protocol. 

Duplicate of #140

**Comment by sherlock-admin4** [comment]
1 comment(s) were left on this issue during the judging contest.

**takarez** commented:
>  there'll be a safer mechanism as the code commets says; that means it will not go into production like this.

**Comment by santipu03** [comment]
Escalate 

This issue shouldn't be a duplicate of #140 and should be marked as a solo MEDIUM.

 As I've explained in a comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2039971451), only my issue out of the 3 duplicates clearly describes the valid impact, that is that whitelisted makers will create bad debt on the protocol if they're not liquidated, causing a loss of funds. 

Issue #140 explains that the impact will be that traders won't be able to close their positions on time, but that impact is not valid as stated by the LSW [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2039482116). Also, issue #44 doesn't uncover the impact that this issue will cause, making this issue (#65) a solo finding. 

It's true that is expected that whitelisted makers won't get liquidated, but this feature will create bad debt on the protocol, as I've explained in my report. Therefore, because it will cause a loss of funds on the protocol, I think it should be considered a valid medium. Given that the README doesn't state anything about this issue, it should be valid as per the Sherlock rules for valid issues.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> This issue shouldn't be a duplicate of #140 and should be marked as a solo MEDIUM.
> 
>  As I've explained in a comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2039971451), only my issue out of the 3 duplicates clearly describes the valid impact, that is that whitelisted makers will create bad debt on the protocol if they're not liquidated, causing a loss of funds. 
> 
> Issue #140 explains that the impact will be that traders won't be able to close their positions on time, but that impact is not valid as stated by the LSW [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2039482116). Also, issue #44 doesn't uncover the impact that this issue will cause, making this issue (#65) a solo finding. 
> 
> It's true that is expected that whitelisted makers won't get liquidated, but this feature will create bad debt on the protocol, as I've explained in my report. Therefore, because it will cause a loss of funds on the protocol, I think it should be considered a valid medium. Given that the README doesn't state anything about this issue, it should be valid as per the Sherlock rules for valid issues. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
As per comment in #140, [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2039482116), I believe it is a known issue within code comments that whitelisted maker cannot be liquidated

**Comment by santipu03** [comment]
It's true that the code comments state that it's not allowed to liquidate whitelisted makers. However, not doing so will create bad debt on the protocol, causing a loss for all participants. 

I created the escalation under the assumption that, in case of conflict between code comments and the Sherlock rules for valid issues, the Sherlock rules override the code comments, as stated in the Sherlock docs:

> Hierarchy of truth: Contest README > Sherlock rules for valid issues > protocol documentation (including code comments) > protocol answers on the contest public Discord channel.
While considering the validity of an issue in case of any conflict the sources of truth are prioritized in the above order.
For example: In case of conflict between information in the README vs Sherlock rules, the README overrides Sherlock rules.

Since the contest README doesn't talk about this issue, it seems like it should be valid according to the rules.

Moreover, we can take other accepted issues as an example of this rule:
- [Issue 133](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/133) is taking the funding fee intended design (as stated in the docs and comments) and using it to cause a loss of funds
- [Issue 126](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/126) is also taking the borrowing fee intended design (as stated in the docs and comments) and using it to cause a loss of funds.

**Comment by WangSecurity** [comment]
@santipu03 Need clarification from the Watson. The point of your report is that this intended design will lead to loss of funds for traders?

**Comment by santipu03** [comment]
The **root cause** (whitelisted makers cannot get liquidated) is the intended design as per the code comments. 
The **impact** (bad debt and loss of funds) is not mentioned anywhere and was not expected, that's why I'm reporting this issue. 

If I'm not mistaken this should be valid, right?
Lots of issues reported in this contest are based on using the intended design of the code and using it to cause some sort of damage or loss of funds.

**Comment by WangSecurity** [comment]
The hierarchy of truth can be applied when there is conflicting information between the code and the rules, but the code and documentation can be used to define the intended design and known issues of the protocol. We understand that it's a bit confusing, but hope for your understanding. Therefore, I agree it's an intended design and a known issue.

Planning to reject the escalation and leave the issue as it is.

**Comment by santipu03** [comment]
I know it's a design decision that whitelisted makers cannot get liquidated. However, if this design decision causes a **loss of funds** the issue should be valid as per the Sherlock rules right?:

> Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.

Moreover, if this issue gets invalidated, other issues in this contest should also be invalidated following this rule:
1. The root cause of [issue 133](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/133) (funding fee gets calculated based on OracleMaker but applied to the entire market) is also the intended design as outlined by the docs [here](https://perp.notion.site/Long-Short-Skew-Funding-Fee-fd7af74f74644209baf0ffb562dc4271):
    > Funding rate is decided by the long/short ratio in base pool (oracle maker)

2. The root cause of [issue 126](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/126) (borrowing fees are payed to makers based on its utilization ratio) is also the intended design as per the docs [here](https://perp.notion.site/Borrowing-Fee-Spec-v0-8-0-22ade259889b4c30b59762d582b4336d).
    > Can receive borrowing fee based on its utilization ratio.

3. The root cause of [issue 127](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/127) (the funding rate formula depends on the LP funds) is also the intended design as is described in the formula of the docs [here](https://perp.notion.site/PythOraclePool-e99a88be051f4bc8be0b1310eb982cd4).
    > maxCapacity = basePool.totalDepositedAmount / basePool.minMarginRatio


@WangSecurity 
Feel free to correct me but in my opinion, this issue and the three mentioned above are the same in the sense that its **root cause is not a bug in the implementation but a flaw in its design** that may cause a loss of funds, and thus they should be valid.

**Comment by WangSecurity** [comment]
Yes, you're correct, but as I've said it's not only the intended design, but also known issue per the code comments. Therefore, I still stand by my previous points to reject the escalation and leave the issue as it is.

If there were no such comments, then this issue would be valid.

**Comment by santipu03** [comment]
The code only states the following [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L166-L168):

```solidity
        // We don't allow liquidating whitelisted makers for now until we implement safety mechanism
        // For spot-hedged base maker, it needs to implement rebalance once it got liquidated
        if (_isWhitelistedMaker(params.marketId, params.trader)) {
            revert LibError.CannotLiquidateWhitelistedMaker();
        }
```

The code comments acknowledges that whitelisted makers cannot get liquidated, that is the intended design. However, the loss of funds caused by this decision is not acknowledged anywhere, therefore is not a known issue but an unexpected consequence caused by the intended design.

**Comment by WangSecurity** [comment]
I understand your arguments and I agree that there may be a loss of funds, but the protocol is aware and this is the intended design on their part. As proof, you can see this [comment](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/140#issuecomment-2018008048) from the protocol. 
Additionally, Sherlock's rules don't allow me to make it a valid issue because NatSpec is also part of the documentation and is a "known issue". For these two reasons, I will have to reject your escalation and leave the issue as it is.

**Comment by santipu03** [comment]
First, the mentioned comment from the protocol devs was stated AFTER the audit finished, therefore cannot be considered a known issue based on that. 

Second, nowhere in the code (or in the docs) is stated that not letting liquidate whitelisted makers will cause some damage. The only related NatSpec comment was the one I showed you in my last comment, and that didn't acknowledge that the design of not liquidating makers will cause some sort of damage. 

As I've said before, the code comments just describe the intended design, not knowing that this design will cause a great loss of funds for the users. That's why this issue should be valid, just as 133, 126 or 127 for the reasons I stated in a previous comment.

**Comment by WangSecurity** [comment]
My judgement wasn't based on the comment I linked you to, this comment is only a proof. I understand that hierarchy of truth and the phrasing of the code comments pose ambiguity in this scenario. Main reason for invalidating here is that it's known issue, and as you see in #133, #126 and #127 (the last is invalid btw) they're exploited by a 3rd party, where in this report as I udnerstand the protocol works as expected and will get into unfavourable state just by its workflow, not because of others exploiting and extracting value from it.

**Comment by santipu03** [comment]
So it all boils down to whether the bug is caused by a 3rd party or by the protocol itself? Honestly, it's the first time in an audit contest that I've seen this argument. I thought the impact of an issue had to be evaluated by itself, not by the actor who caused it.

And you keep stating that this is a known issue but I've demonstrated over and over again that there's not a statement within the README, NatSpec, or documentation that acknowledges the risk of not liquidating a whitelisted maker.

**Comment by WangSecurity** [comment]
I don't say that "whether the bug is caused by a 3rd party or by the protocol itself" is the my reasoning, I'm trying to show why this report is different from the three issues you mentioned.

I understand that in this case nowhere is said that whitelisted makers causing a bad debt is a known issue, but from the comments you provided (an the ones we discussed before) we believe it's a known issue. By "we" I mean that I've consulted with both Evert and Tsvetanov and we all agree this should be considered as a known issue. Plus as you can see in report #140 in comments by the judges right under the report, they also see it as a known issue. The comment from the sponsor a linked in previous comments is just a proof that our understand was correct regarding this. Moreover, in the same comments you've sent, we can see that the team will implement a safer mechanism which can be assumed as they understand it's not safe.

What I mean here is that my judgement is based only on the "known issue" factor, other things was used to show that your report is different from others and there lots of other factors which leads to making different decision on every issue. Finally, when I first read this report I thought it indeed can be med, but as I've said, after consulting with other judges, this issue should remain excluded and the escalation - rejected.

**Comment by santipu03** [comment]
I see that you've already made up your mind regardless of what arguments I can provide so I will accept the decision. 

I just think this can set a bad precedent for the Watsons who go that extra mile to find how the intended design of a protocol can cause a loss of funds and damage its users. I know now how these kind of findings are judged so I will take notes for next contests.

**Comment by WangSecurity** [comment]
Thank you very much for your understanding, I see that there is a certain ambiguity in how to understand what is "known issue" and how to treat the hierarchy of truth and we're working on it. We can loop @Evert0x here to take another look at it and maybe we redecide on this one, but as of know I remain my decision to reject the escalation and leave the issue as it is.

**Comment by santipu03** [comment]
I'd appreciate it if @Evert0x could also take a look at this issue and express their opinion on this. 

I agree that the Sherlock docs may need an update regarding the definitions of "known issue" and the hierarchy of truth. This way in the future we can save some time arguing about those definitions on the escalations.

**Comment by Evert0x** [comment]
First, the ambiguity in the hierarchy of truth is evident. We will make changes to this language soon.

However, based on my interpretation I believe that JUDGING RULES should be used as the truth in case there is a conflict between the JUDGING RULES and the CODE COMMENTS. For that reason, this issue should be valid.

This report (65) identifies the core issues and identifies a valid impact
#140 identifies the same root cause but also identifies a valid impact. 
#44 doesn't identify a valid impact.

I believe 140 should become Medium with 65 as a duplicate.

Planning to accept escalation and revert the escalation decision on 140.

**Comment by IllIllI000** [comment]
@Evert0x the JUDGING RULES say that [this](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/121#issuecomment-2039394011) finding is valid, since it's a code comment, does it not? I don't see what the difference is between this finding and mine

**Comment by santipu03** [comment]
@Evert0x 
Thanks for the resolution, I agree that the judging rules need some changes in order to save time for both watsons and judges. 

However, I believe that the impact identified by issue #140, that is the positions won't close because of lack of liquidity, was declared invalid by @WangSecurity [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/90#issuecomment-2076701904).

**Comment by Oot2k** [comment]
Yes I dont understand how this issue is valid if #90 is invalid and #64 + #106 are also invalid. 

90 has a similar impact to this: discouraged liquidations = bad dept. 
And in addition to this I also dont understand why #121 is invalid. It has the same idea of "Comment states known issue so invalid"

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #140

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/65/#issuecomment-2040022930): accepted

**Comment by santipu03** [comment]
@Evert0x I don't think that the impact of issue #140 is valid. 

Issue #140 states that the impact is the inability to close a position due to the lack of liquidity. However, that impact was declared invalid by @WangSecurity [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/90#issuecomment-2076701904).

**Comment by WangSecurity** [comment]
Thank you for notice, both #65 and #140 explain very similar scenario of how this vulnerability can occur:

1. Market is skewed towards ons side (long or short).
2. Price starts to move against the Maker's position.
3. Maker enters a loss and there is not enough margin to cover it.

#140 takes it a bit further and says that it will lead to inability to close positions, due to lack of liquidity (which as you correctly noticed is judged invalid), but still the scenario and core vulnerability are almost the same in these two reports. Hence, #140 is sufficient enough to be duped with this report.
