### ISSUE TITLE
santipu_ - `MakerReporter` not accounting for unrealized PnL on whitelisted makers leads to inaccurate borrowing fee

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-perpetual-judging#68]
santipu_

medium

# `MakerReporter` not accounting for unrealized PnL on whitelisted makers leads to inaccurate borrowing fee

## Summary

The margin of the whitelisted makers is key for calculating its utilization rate, which is key for calculating the borrowing rate. The borrowing fee is the fee that all traders will pay to whitelisted makers in exchange for providing liquidity to the market. However, the current calculations of the borrowing rate do not include the unrealized PnL on the maker's margin, leading to an inaccurate borrowing fee when makers haven't settled a position in a while. 

## Vulnerability Detail

The purpose of the borrowing fee is to make traders pay to whitelisted makers in exchange for them providing guaranteed liquidity in all conditions, without taking liquidity from others. The borrowing fee is based on the borrowing rate, which is defined as the following:

$$
\\
borrowingRate := maxBorrowingFeeRate \times utilizationRatio
\\
$$

The variable `maxBorrowingFeeRate` is a governance-defined value and `utilizationRatio` is defined as the weighted average of the utilization ratio of all whitelisted makers (`OracleMaker` and `SpotHedgeBaseMaker`). 

The utilization ratio of whitelisted makers is calculated via a special contract called `MakerReporter`, this is done to avoid manipulations by whitelisted makers. The function that returns the utilization ratio of a whitelisted maker is the following:

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/makerReporter/MakerReporter.sol#L35-L63
```solidity
    function getUtilRatioFactor(uint256 marketId, address receiver) external view returns (uint256, uint256) {
        IVault vault = getAddressManager().getVault();
        int256 margin = vault.getMargin(marketId, receiver);
        int256 openNotional = vault.getOpenNotional(marketId, receiver);
        uint256 defaultUtilRatio;
        if (margin <= 0) {
            defaultUtilRatio = WAD;
        } else {
            // margin > 0, can type to uint directly
            uint256 positiveMargin = uint256(margin);
            defaultUtilRatio = FixedPointMathLib.min(WAD, openNotional.abs().divWad(positiveMargin));
        }

        uint256 openNotionalAbs = openNotional.abs();
        uint256 defaultUtilRatioFactor = defaultUtilRatio * openNotionalAbs;

        if (openNotional < 0) {
            return (0, defaultUtilRatioFactor);
        }
        return (defaultUtilRatioFactor, 0);
    }
```

This function calculates the utilization ratio of a whitelisted maker by applying the following formula:

$$
\\
utilizationRatio := \frac{abs(openNotional)}{margin}
\\
$$

However, the margin used to calculate the utilization ratio does not take into account the unrealized PnL. This will cause that when a whitelisted maker has some unrealized profits/losses, the resulting borrowing rate will be inaccurate, making traders pay too much or too little. 

## Impact

When `OracleMaker` or `SpotHedgeBaseMaker` (whitelisted makers) haven't settled a position in a while and the price has changed, the unrealized PnL won't be included in the calculation of the borrowing rate, leading to an inaccurate fee that traders will have to bear with. 

For example, when a whitelisted maker has unrealized profits, its margin will be bigger, which should drive its utilization rate lower, leading to a lower borrowing fee. However, because the borrowing rate is not taking unrealized PnL into account, the borrowing fees will continue to be higher than they should, leading to traders paying too much fees during that period. 

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/makerReporter/MakerReporter.sol#L37

## Tool used

Manual Review

## Recommendation

To mitigate this issue is recommended to include the unrealized PnL in the calculations for the borrowing rate. The following is the proposed fix for `MakerReporter` to mitigate the issue:

```diff
-   function getUtilRatioFactor(uint256 marketId, address receiver) external view returns (uint256, uint256) {
+   function getUtilRatioFactor(uint256 marketId, address receiver, uint256 price) external view returns (uint256, uint256) {
        IVault vault = getAddressManager().getVault();
-       int256 margin = vault.getMargin(marketId, receiver);
+       int256 margin = vault.getAccountValue(marketId, receiver, price);
        int256 openNotional = vault.getOpenNotional(marketId, receiver);
        uint256 defaultUtilRatio;
        // ...
    }
```

**Comment by sherlock-admin3** [comment]
2 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Medium

**takarez** commented:
>  this seem valid to me as the margin should include the unrealized pnl in order to accurately calculate the borrowing fees.; medium(4)

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/perpetual-protocol/perp-contract-v3/pull/18

**Comment by IllIllI000** [comment]
@nevillehuang the [documentation](https://perp.notion.site/Borrowing-Fee-Spec-v0-8-0-22ade259889b4c30b59762d582b4336d) for this feature does not say anything about the need to include unrealized pnl in the calculation, and the code indeed does follow the stated formula of `abs(openNotional)/margin`. This submission suggests to change the formula to `abs(openNotional)/accountValue` instead, which is a design decision about how to define utilization, not a security issue.

**Comment by nevillehuang** [comment]
See comments [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/69#issuecomment-2022061326) and agree with @IllIllI000 comment [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68#issuecomment-2030170900)

**Comment by santipu03** [comment]
Escalate

I think this issue should be MEDIUM.

According to the docs, the utilization ratio of a maker is defined with the following formula:

$$
\text{utilizationRatio} = \frac{abs(openNotional)}{margin}
$$

Therefore, to calculate the current utilization ratio of a maker, we should use the CURRENT margin of that maker, and that includes the unrealized PnL. To clarify again, the unrealized PnL is the accrued profits or losses since the last time that position was updated. 

When we do not include the unrealized PnL in the margin, the resulting margin will be calculated as if the price hasn't changed since the last update of the position. In a scenario where the position of a maker hasn't been updated in a while and the price has changed since then, the resulting utilization ratio will be stale, therefore resulting in an inaccurate borrowing fee. 

The borrowing fee is a key component in the Perpetual protocol because it incentivizes users to deposit liquidity in whitelisted makers. When the borrowing fee is inaccurate, we may encounter two scenarios:

1. **Borrowing fee is higher than it should be**: In this case, all positions that are not whitelisted makers will have to pay too much borrowing fees, and that will push some positions into liquidation. 
2. **Borrowing fee is lower than it should be**: In this case, all positions that are not whitelisted makers will pay too little fees to whitelisted makers, therefore defeating the original purpose of the borrowing fee, which is incentivizing LPs. 

Given that this issue clearly points out scenarios where the resulting borrowing fee will be inaccurate, and that will cause a loss of funds, I think this issue should have a medium severity. Moreover, the sponsors already confirmed the issue and fixed it, confirming my point.

I'd like to ask the Lead Judge to reevaluate the severity of this issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this issue should be MEDIUM.
> 
> According to the docs, the utilization ratio of a maker is defined with the following formula:
> 
> $$
> \text{utilizationRatio} = \frac{abs(openNotional)}{margin}
> $$
> 
> Therefore, to calculate the current utilization ratio of a maker, we should use the CURRENT margin of that maker, and that includes the unrealized PnL. To clarify again, the unrealized PnL is the accrued profits or losses since the last time that position was updated. 
> 
> When we do not include the unrealized PnL in the margin, the resulting margin will be calculated as if the price hasn't changed since the last update of the position. In a scenario where the position of a maker hasn't been updated in a while and the price has changed since then, the resulting utilization ratio will be stale, therefore resulting in an inaccurate borrowing fee. 
> 
> The borrowing fee is a key component in the Perpetual protocol because it incentivizes users to deposit liquidity in whitelisted makers. When the borrowing fee is inaccurate, we may encounter two scenarios:
> 
> 1. **Borrowing fee is higher than it should be**: In this case, all positions that are not whitelisted makers will have to pay too much borrowing fees, and that will push some positions into liquidation. 
> 2. **Borrowing fee is lower than it should be**: In this case, all positions that are not whitelisted makers will pay too little fees to whitelisted makers, therefore defeating the original purpose of the borrowing fee, which is incentivizing LPs. 
> 
> Given that this issue clearly points out scenarios where the resulting borrowing fee will be inaccurate, and that will cause a loss of funds, I think this issue should have a medium severity. Moreover, the sponsors already confirmed the issue and fixed it, confirming my point.
> 
> I'd like to ask the Lead Judge to reevaluate the severity of this issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@CheshireCatNick @paco0x I think based on your comments in [#69 here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/69#issuecomment-2022061326), wasn't this the original intended design? From @santipu03 comment above, I can see the borrowing fee indeed has the potential to be higher/lower than it should be, but what was the design tradeoff previously considered?

@santipu03 What is the difference between #67, #68 and #69? In my opinion they all have extremely similar root causes just with different impact and should be duplicated with each other if this issue is valid as per sherlock duplication rules

**Comment by paco0x** [comment]
> @CheshireCatNick @paco0x I think based on your comments in [#69 here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/69#issuecomment-2022061326), wasn't this the original intended design? From @santipu03 comment above, I can see the borrowing fee indeed has the potential to be higher/lower than it should be, but what was the design tradeoff previously considered?
> 
> @santipu03 What is the difference between #67, #68 and #69? In my opinion they all have extremely similar root causes just with different impact and should be duplicated with each other if this issue is valid as per sherlock duplication rules

yes we know that the rate will be higher/lower than it should be in the original design, and after some discussions, we decided to change the original design and follow the suggestions here. Even if we use the original design, the impact of this issue should not be significant.

But since we already followed the suggestions here and changed our code, we're open to make it a valid finding.

**Comment by santipu03** [comment]
> @santipu03 What is the difference between https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/67, https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68 and https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/69? In my opinion they all have extremely similar root causes just with different impact and should be duplicated with each other if this issue is valid as per sherlock duplication rules

**Issue 67:**
- Root cause: Funding rate is not accounting for unrealized PnL
- Impact: Funding fee will be inaccurate, causing a loss of funds for traders or LPs

**Issue 68:**
- Root cause: Utilization ratio on whitelisted makers is not accounting for unrealized PnL
- Impact: Funding fee will be too high/low, causing losses to traders.

**Issue 69:**
- Root cause: The position rate of OracleMaker does not include unrealized profits
- Impact: Price spread will be bigger, causing losses to traders that open positions with OracleMaker

In my opinion, the three issues have different root causes, different impacts and different mitigations. 
Even if we consider the three issues the "_same vulnerability_", they shouldn't be duplicated as per the Sherlock docs:
>  In case the same vulnerability appears across multiple places in different contracts, they can be considered duplicates.
The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately.

**Comment by nevillehuang** [comment]
I believe #67, #68 and #69 to be medium severity and duplicates where in not accounting for unrealized PnL results in three separate impacts. @paco0x do you agree?

**Comment by paco0x** [comment]
> I believe #67, #68 and #69 to be medium severity and duplicates where in not accounting for unrealized PnL results in three separate impacts. @paco0x do you agree?

agree

**Comment by IllIllI000** [comment]
@nevillehuang `In a scenario where the position of a maker hasn't been updated in a while and the price has changed since then, the resulting utilization ratio will be stale, therefore resulting in an inaccurate borrowing fee.` The design of the system, as was outlined in the docs, was to not take into account unrelized PnL in the arbitrary formulas used for funding, borrow, and OM spread. You can think of this as a sliding scale of how frequently the maker settles its trades, and therefore updates its rates. The design in the docs is that the OM updates its rates whenever someone trades with it (because there's no unrealized PnL once you've settled and _realized_ the PnL). Another possible design is to update rates whenever anyone trades not just with the OM, but with _anyone_ else. Yet another possible design is to have a keeper that periodically updates every so often. The design where things will never be 'stale' is to have a keeper that updates during every block (very expensive). This submission is claiming that not doing the `anyone else` variant is a security issue, which it is not. If it's a security issue, then it would also be a security issue to not sync during every block, which it certainly is _not_.

**Comment by WangSecurity** [comment]
I agree with the comment by @IllIllI000 above. This report is a design improvement to calculation of the borrowing fee. The formula in the code follows the one from the docs. Hence, I believe it's not a security issue, but the design advice, despite the fact that the team applied the fix.

Planning to reject the escalation and leave the issue as it is.

**Comment by santipu03** [comment]
> The design of the system, as was outlined in the docs, was to not take into account unrelized PnL in the arbitrary formulas used for funding, borrow, and OM spread.

Where in the docs is outlined that the unrealized PnL is not accounted for in those formulas?

For example, let's take a look at the [borrowing fee docs](https://perp.notion.site/Borrowing-Fee-Spec-v0-8-0-22ade259889b4c30b59762d582b4336d):
1. The docs state the whitelisted makers receive borrowing fee based on their utilization ratio
2. The utilization ratio is defined by the following formula:

$$
utilizationRatio := \begin{cases}
Min(1, \cfrac{Abs(openNotional)}{margin}) &\text{if margin > 0}
\\
1 &\text{if margin <=0}
\end{cases}
$$

It's implied that the word "_margin_" in the formula is the CURRENT margin, not the margin as per the last time the whitelisted maker settled a position. In order for the margin to represent its current value and not a stale one, the implementation in the docs **must** include the unrealized PnL of the whitelisted maker. 

There's not a place within the borrowing and funding fee docs where it states that the unrealized PnL is not accounted for. In both docs, it's assumed that the margin used for the calculations is the CURRENT margin, not a STALE one. 

P.S. Btw, I don't think issue #69 warrants medium severity, that's why I didn't escalate it. It shouldn't be grouped with #67 and #68.

**Comment by WangSecurity** [comment]
@santipu03 is it said in the docs that the margin indeed represents both realised and unrealised PnL? And do I understand correctly that by settled positions you mean closed ones, i.e. right now it takes into account only the realised PnL?

**Comment by santipu03** [comment]
The docs don't mention unrealized PnL but when they mention the _**margin**_ it's assumed that they're taking the _current_ margin, which includes the unrealized PnL. It makes no sense that the docs use the word _margin_ to refer to a stale margin and not the current value. That's why this issue is a bug in the implementation, not a design improvement issue. 

When I say that the whitelisted maker settles positions, I mean its opening or closing positions for traders, adjusting its own position (because it's the counterparty to traders).

**Comment by WangSecurity** [comment]
Unfortunately, then to me it looks like the the formula is indeed the same as in the docs and saying that "margin" should also take into account "unrealisedPnL" is an assumption. Hence, I still believe [this](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68#issuecomment-2030170900) comment by @IllIllI000 is correct and this report is a design decision, not a security issue.

Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/68/#issuecomment-2037717625): rejected

**Comment by sherlock-admin3** [comment]
The Lead Senior Watson signed off on the fix.
