### ISSUE TITLE
PUSH0 - Sequencer outage will create mass liquidations

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#78]
PUSH0

medium

# Sequencer outage will create mass liquidations

## Summary

If the sequencer experiences an outage, the price might fluctuate and create a surge in illiquid positions. 
Once the sequencer is restored, there's no way to prevent the liquidation of your position, 
resulting in losses for the trader.

## Vulnerability Detail

Sequencer outages can happen for several reasons, this can include upgrades (like OPs bedrock upgrade in 2023) or issues.
(like blasts recetent problem).

This will prevent traders from toping up their positions to prevent liquidation, in case the price moves into an unfavorable direction.
When the sequencer goes online again, these positions can be liquidated, leading to the trader losing his position.

## Impact

Trader losing his position without having the possibility to top it up, will lead to loss of funds for him.

## Code Snippet

https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/oracle/pythOracleAdapter/PythOracleAdapter.sol#L51

## Tool used

Manual Review

## Recommendation

Add a grace period after the sequencer outage.
This can be achieved by checking for sequencer outage on get oracle price and returning a stale price in case outage is detected.
After a short grace period price will update and liquidate in case trader does not deposit more margin.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**santipu_** commented:
> Invalid according to Sherlock rules

**Comment by nevillehuang** [comment]
Invalid based on the following sherlock [rule](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid), wherein external admins of optimism/blast are noted as trusted

> 20. Chain re-org and network liveness related issues are not considered valid.
Exception: If an issue concerns any kind of a network admin (e.g. a sequencer), can be remedied by a smart contract modification, the protocol team considers external admins restricted and the considered network was explicitly mentioned in the contest README, it may be a valid medium. It should be assumed that any such network issues will be resolved within 7 days, if that may be possible.

**Comment by lepLinus** [comment]
escalate

I think this issue is incorrectly excluded. The protocol will be deployed on OP and blast, two networks which are known for being offline once in a while. 
Most notably: 
https://decrypt.co/221538/ethereum-layer-2-blast-outage-dencun-upgrade
Or the bedrock upgrade on OP.

Perpetual contracts are meant to be opened and kept open for undefined time, which means it is likely to happen that positions stay open while sequencer goes down. Because of high leverage they can easily go under water, which will lead to mass liquidations after sequencer is online again.
Fixing this issue is quite simple, just call chain link oracle to check for uptime.
In combination with other problems around liquidations, I believe in this case network liveness should be considered a valid medium finding, especially based on recent events.

**Comment by sherlock-admin2** [comment]
> escalate
> 
> I think this issue is incorrectly excluded. The protocol will be deployed on OP and blast, two networks which are known for being offline once in a while. 
> Most notably: 
> https://decrypt.co/221538/ethereum-layer-2-blast-outage-dencun-upgrade
> Or the bedrock upgrade on OP.
> 
> Perpetual contracts are meant to be opened and kept open for undefined time, which means it is likely to happen that positions stay open while sequencer goes down. Because of high leverage they can easily go under water, which will lead to mass liquidations after sequencer is online again.
> Fixing this issue is quite simple, just call chain link oracle to check for uptime.
> In combination with other problems around liquidations, I believe in this case network liveness should be considered a valid medium finding, especially based on recent events.  

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by Oot2k** [comment]
escalate

I think this issue is incorrectly excluded. The protocol will be deployed on OP and blast, two networks which are known for being offline once in a while. 
Most notably: 
https://decrypt.co/221538/ethereum-layer-2-blast-outage-dencun-upgrade
Or the bedrock upgrade on OP.

Perpetual contracts are meant to be opened and kept open for undefined time, which means it is likely to happen that positions stay open while sequencer goes down. Because of high leverage they can easily go under water, which will lead to mass liquidations after sequencer is online again.
Fixing this issue is quite simple, just call chain link oracle to check for uptime.
In combination with other problems around liquidations, I believe in this case network liveness should be considered a valid medium finding, especially based on recent events.

**Comment by sherlock-admin2** [comment]
> escalate
> 
> I think this issue is incorrectly excluded. The protocol will be deployed on OP and blast, two networks which are known for being offline once in a while. 
> Most notably: 
> https://decrypt.co/221538/ethereum-layer-2-blast-outage-dencun-upgrade
> Or the bedrock upgrade on OP.
> 
> Perpetual contracts are meant to be opened and kept open for undefined time, which means it is likely to happen that positions stay open while sequencer goes down. Because of high leverage they can easily go under water, which will lead to mass liquidations after sequencer is online again.
> Fixing this issue is quite simple, just call chain link oracle to check for uptime.
> In combination with other problems around liquidations, I believe in this case network liveness should be considered a valid medium finding, especially based on recent events.  

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
This should remain invalid based on my comments [here](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/78#issuecomment-2021793240)

**Comment by WangSecurity** [comment]
Agree with the Lead Judge. External admins are trusted, hence under the rule mentioned by Nevi above. Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Oot2k](https://github.com/sherlock-audit/2024-02-perpetual-judging/issues/78/#issuecomment-2037667055): rejected
