### ISSUE TITLE
Kose - SpotHedgeBaseMaker is Vulnerable to Price Manipulation Attacks Because Insufficient Slippage Protection

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-perpetual-judging#92]
Kose

medium

# SpotHedgeBaseMaker is Vulnerable to Price Manipulation Attacks Because Insufficient Slippage Protection

## Summary
SpotHedgeBaseMaker lacks protection against slippage, exposing makers to potential fund losses.
## Vulnerability Detail
When SpotHedgeBaseMaker is the maker for an openPosition call, it initiates a swap of the same amount via UniSwap to hedge its position. However, during this swap, slippage parameters --specifically "amountOutMinimum" if IsExactInput is 0, and "amountInMaximum" if IsExactOutput equals the balance(address(this))-- are not enforced:
```solidity
            if (isExactInput) {
                uint256 baseTokenRequired = _formatPerpToSpotBaseDecimals(amount);
                quoteTokenAcquired = _uniswapV3ExactInput(
                    UniswapV3ExactInputParams({
                        tokenIn: address(_getSpotHedgeBaseMakerStorage().baseToken),
                        tokenOut: address(_getSpotHedgeBaseMakerStorage().quoteToken),
                        path: path,
                        recipient: maker,
                        amountIn: baseTokenRequired,
                        amountOutMinimum: 0
                    })
                );
                oppositeAmount = _formatSpotToPerpQuoteDecimals(quoteTokenAcquired);
                // Currently we don't utilize fillOrderCallback for B2Q swaps,
                // but we still populate the arguments anyways.
                fillOrderCallbackData.amountXSpotDecimals = baseTokenRequired;
                fillOrderCallbackData.oppositeAmountXSpotDecimals = quoteTokenAcquired;
            } else {
                quoteTokenAcquired = _formatPerpToSpotQuoteDecimals(amount);
                uint256 oppositeAmountXSpotDecimals = _uniswapV3ExactOutput(
                    UniswapV3ExactOutputParams({
                        tokenIn: address(_getSpotHedgeBaseMakerStorage().baseToken),
                        tokenOut: address(_getSpotHedgeBaseMakerStorage().quoteToken),
                        path: path,
                        recipient: maker,
                        amountOut: quoteTokenAcquired,
                        amountInMaximum: _getSpotHedgeBaseMakerStorage().baseToken.balanceOf(maker)
                    })
```

 This means that slippage is not considered during the swap process. The sole slippage check occurs after the swap, through checkPriceBand() in ClearingHouse, once HedgeMaker returns the exact amounts from the UniSwap swap. However, this priceBand check does not fully safeguard against slippage, as it only verifies that the amount falls within a range of ±10% of the PythOracle price. Consequently, it remains possible to exploit HedgeMaker through price manipulation, resulting in potential gains of up to 10%.
## Impact
The vulnerability allows for value extraction from HedgeMaker, consequently affecting its liquidity providers. This results in gains for traders but leads to fund losses for liquidity providers. Additionally, accounting issues may arise within HedgeMaker due to the drop in its marginRatio following these swaps.
## Code Snippet
https://github.com/sherlock-audit/2024-02-perpetual/blob/main/perp-contract-v3/src/maker/SpotHedgeBaseMaker.sol/#L398-L425
## Tool used

Manual Review

## Recommendation
Reducing the priceBand won't resolve this issue and could potentially create additional problems, such as reverting benign transactions. Since pythPriceOracle is already utilized in ClearingHouse's openPosition() call (even when the maker is HedgeMaker which uses UniSwap), extending its use during the swap call and constraining the output from the swap (slippage) accordingly can effectively address the problem.

**Comment by nevillehuang** [comment]
Invalid, slippage checks performed [here](https://github.com/sherlock-audit/2024-02-perpetual/blob/02f17e70a23da5d71364268ccf7ed9ee7cedf428/perp-contract-v3/src/clearingHouse/ClearingHouse.sol#L309-L329) within ClearingHouse contract

**Comment by kosedogus** [comment]
@nevillehuang and @Czar102 is it possible for this to be checked again please? 
This issue should be a duplicate of #119. I believe the name of the issue created some misconception. I didn't explicitly showed how price can be manipulated like #119 and #77 because I though it is a well known concept and the path is clear. I also mentioned the attack is restricted up to what priceBand allow, just like both of those issues. Also my recommendation is completely same with what #77 recommends and my impact is also same with both of those issues. Only missing part is word **sandwich**, but isn't **price manipulation** is enough in this case? Changing uniswap's returned amount with price manipulation indeed inherently requires sandwiching, and I believe it should be clear what this issue explain is exactly same with aforementioned issues if you can read them back to back.

I can't escalate unfortunately because I wasn't using Sherlock since the August and new rules regarding escalations created a problem for me. I would appreciate it if you can check it.

**Comment by kosedogus** [comment]
@WangSecurity Sir, can you check also this one please? It is just a duplication request, I believe it is overlooked unfortunately. I would be very happy if you can check it. Thank you.

**Comment by WangSecurity** [comment]
The problem of this report is that it doesn't clearly describe how the attacker can exploit it. I understand that you wrote price manipulation, but both #119 and #77 explicitly explain how the attack would look. Hence, I believe it's not a sufficient enough to be considered a duplicate. 

For future, try to make your reports as concise as possible and ask other watsons in discord to escalate this issues on your behalf, there are lots of watsons who will do that.

**Comment by kosedogus** [comment]
@WangSecurity Thank you sir, but I want to ask the following, according to *Criteria for Issue Validity* docs, we should be in scenario A currently I believe. Which is following:
> Scenario A:
>  There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attack paths: 
> - B -> high severity path
> - C -> medium severity attack path/just identifying the vulnerability.
> Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put  together as duplicates.
> - In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.

Isn't this issue which "identifies the vulnerability" is *C* ? If so, isn't that make it a valid duplicate?

**Comment by kosedogus** [comment]
@WangSecurity Thank you sir, but I want to ask the following, according to *Criteria for Issue Validity* docs' duplication rules we have this before even going into scenarios:
> Issues identifying a core vulnerability can be considered duplicates.

Then docs continue to clarify issues when they have different attack paths etc. The main issue in here is medium with all it's duplicates. Main issue and it's duplicates are showing the attack path while mine issue only specifies the core vulnerability because I thought attack path is obvious (which I will be more careful now on, thank you for suggestion). But isn't duplication rules suggest this submission is also sufficient? What am I missing here, can you please clarify?

**Comment by WangSecurity** [comment]
Very good question. There is a very thin border in duplication rules when issue identifying the vulnerability may be either a duplicate or not. But, unfortunately, there is also another reason. The escalation ratio was presented to avoid situations when too many issues escalated, hence, I cannot make it a duplicate now, since it's not escalated. Regardless of how to interpret the duplication rule, I cannot do that unfortunately.

Therefore, I can only give the advice to either make your reports as explicit as it can be and ask others to escalate on your behalf. As I see on discord, you didn't to that, hence, ask the next time. But, unfortunately, I cannot change the decision. Hope you understand and thank you for calm and polite reply.

**Comment by kosedogus** [comment]
Thank you for explanation sir, I didn't tried to escalate my issue with the help of fellow watsons because I saw that non-escalated issues' situation also changes sometimes after escalation period and we have this in *Escalation Period* documentation:
> Any request to resolve issues outside of the escalation period is not guaranteed to be addressed.

So, I thought it was up to judge's good will to resolve request for issues even if it is not escalated. If this is not true, then yeah there is nothing to do :crying_cat_face: But then I of course wonder what is the reasoning behind aforementioned line in documentation :/ I would be very happy if you can double check that it is really is not possible according to rules because especially in the recent/ongoing contests it seems like there are indeed judges try to reconsider issues even if they are not escalated. Either way thanks in advanced.

**Comment by WangSecurity** [comment]
Yeah, it happens that we change the decision even if escalation wasn't raised, but it usually happens to invalid issues that were judged as valid. Therefore, cannot help on this one, unfortunately. Wish you all the best next time.
